import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

test('echo workbench owns setup and active echo presentation', async () => {
  const source = await readFile(new URL('./EchoWorkbenchView.vue', import.meta.url), 'utf8')
  const captureSource = await readFile(new URL('./ActiveEchoCapturePanel.vue', import.meta.url), 'utf8')

  assert.match(source, /import \{ sonataEffects \} from '\.\.\/\.\.\/data\/sonataEffects'/)
  assert.match(source, /import \{ mainStatLabels, mainStatsByCost \} from '\.\.\/\.\.\/data\/substats'/)
  assert.match(source, /import ActiveEchoCapturePanel from '\.\/ActiveEchoCapturePanel\.vue'/)
  assert.match(source, /const legalMainStats = computed\(\(\) => mainStatsByCost\[props\.config\.cost\] \|\| \[\]\)/)
  assert.match(source, /const predictionRankings = computed/)
  assert.match(source, /Number\.isFinite\(row\.candidate\?\.p_final\)/)
  assert.match(source, /probability: row\.candidate\.p_final/)
  assert.match(captureSource, /const activeEchoDisplayName = computed/)
  assert.match(source, /:prediction-rankings="predictionRankings"/)
  assert.match(source, /class="product-panel create-panel"/)
  assert.match(source, /class="gallery-panel"/)
  assert.match(source, /ref="sonataGridRef"/)
  assert.match(source, /:aria-current="config\.sonata === effect\.name \? 'true' : null"/)
  assert.match(source, />ECHO SETUP</)
  assert.match(source, /选择套装、COST、主词条后开始录入。/)
  assert.match(captureSource, /activeSonataEffect/)
  assert.match(captureSource, /class="active-echo-stage"/)
  assert.match(captureSource, /class="active-echo-set-badge"/)
  assert.match(captureSource, /class="active-record-panel"/)
  assert.match(captureSource, /class="active-echo-name-title"/)
  assert.match(captureSource, /class="active-record-meta-pills"/)
  assert.doesNotMatch(captureSource, /displayEchoNumericId/)
  assert.doesNotMatch(source, /<span>当前声骸<\/span>/)
  assert.doesNotMatch(source, /<h3 class="active-section-title">当前声骸<\/h3>/)
  assert.doesNotMatch(source, /class="setup-current-summary"/)
  assert.doesNotMatch(source, /class="active-config-chips"/)
  assert.doesNotMatch(source, /class="matrix-guide"/)
})

test('echo setup defaults to continuous tuning without exposing a mode switch', async () => {
  const source = await readFile(new URL('./EchoWorkbenchView.vue', import.meta.url), 'utf8')
  const workflowSource = await readFile(new URL('./useEchoWorkspace.js', import.meta.url), 'utf8')

  assert.doesNotMatch(source, /同一批连续调谐/)
  assert.doesNotMatch(source, /type="checkbox"/)
  assert.doesNotMatch(source, /is_continuous_tuning: \$event\.target\.checked/)
  assert.match(workflowSource, /is_continuous_tuning: true/)
})

test('echo workbench keeps substat rows focused on entry by default', async () => {
  const source = await readFile(new URL('./EchoWorkbenchView.vue', import.meta.url), 'utf8')
  const captureSource = await readFile(new URL('./ActiveEchoCapturePanel.vue', import.meta.url), 'utf8')
  const combinedSource = `${source}\n${captureSource}`

  assert.match(combinedSource, /formatSubstatTierValue/)
  assert.match(captureSource, /class="roll-position"/)
  assert.match(captureSource, /class="roll-name"/)
  assert.match(captureSource, /class="roll-value"/)
  assert.match(captureSource, /class="active-record-head"/)
  assert.match(captureSource, /class="active-record-count-badge"/)
  assert.match(captureSource, /const rollSlots = computed/)
  assert.match(captureSource, /Array\.from\(\{ length: 5 \}/)
  assert.match(captureSource, /<strong class="active-record-count-badge"><span>\{\{ activeEchoSubstats\.length \}\}<\/span><small>\/5<\/small><\/strong>/)
  assert.match(captureSource, /待调谐/)
  assert.match(captureSource, /<b class="roll-value">\{\{ formatSubstatTierValue\(roll\.substat_type, roll\.tier_value\) \}\}<\/b>/)
  assert.match(source, /{{ formatSubstatTierValue\(row\.substat_type, row\.recorded\.tier_value\) }}/)
  assert.match(source, /formatSubstatTierNumber\(row\.substat_type, tier\.value\)/)
  assert.doesNotMatch(source, /副词条记录 \{\{ activeEcho\.substats\.length \}\}\/5/)
  assert.match(captureSource, /activeRecordPills/)
  assert.match(captureSource, /const activeRecordPills = computed\(\(\) => \[\s+props\.activeEcho\?\.set_name \|\| props\.config\.sonata,\s+`COST \$\{previewCost\.value\}`,/)
  assert.match(captureSource, /mainStatLabels\[props\.activeEcho\?\.main_stat \|\| props\.config\.main_stat\]/)
  assert.doesNotMatch(source, /formatPercent\(row\.candidate\.p_final\)/)
  assert.doesNotMatch(source, /formatSignedPercent\(row\.candidate\.baseline_deviation\)/)
  assert.doesNotMatch(source, /<small v-if="row\.candidate">/)
})

test('active echo area uses an immersive preview and record console', async () => {
  const source = await readFile(new URL('./ActiveEchoCapturePanel.vue', import.meta.url), 'utf8')
  const style = await readFile(new URL('../../styles/features/workspace-active.css', import.meta.url), 'utf8')

  assert.match(source, /import \{ sonataEchoesBySetName \} from '\.\.\/\.\.\/data\/sonataEchoes'/)
  assert.match(source, /const activeEchoesForCost = computed/)
  assert.match(source, /const activePreviewEcho = computed/)
  assert.match(source, /class="active-echo-stage"/)
  assert.match(source, /class="active-echo-stage-media"/)
  assert.match(source, /class="active-echo-set-badge"/)
  assert.match(source, /class="active-echo-stage-art"/)
  assert.doesNotMatch(source, /class="active-echo-art-frame"/)
  assert.doesNotMatch(source, /class="active-echo-stage-cost"/)
  assert.doesNotMatch(source, /class="active-echo-name-chip"/)
  assert.match(source, /class="active-record-panel"/)
  assert.match(source, /class="active-record-main"/)
  assert.match(source, /class="active-echo-name-title"/)
  assert.match(source, /class="active-record-meta-pills"/)
  assert.match(source, /class="active-record-pill"/)
  assert.match(source, /class="active-record-count-badge"/)
  assert.match(source, /const activeEchoSubstats = computed/)
  assert.match(source, /const progressSegments = computed/)
  assert.match(source, /class="active-progress-segments"/)
  assert.match(source, /class="roll-slot"/)
  assert.match(source, /:class="\{ pending: roll\.pending \}"/)
  assert.match(source, /<strong class="active-record-count-badge"><span>\{\{ activeEchoSubstats\.length \}\}<\/span><small>\/5<\/small><\/strong>/)
  assert.doesNotMatch(source, /activeEcho\?\.substats\.length/)
  assert.match(source, /class="[^"]*record-actions/)
  assert.match(source, /class="[^"]*active-action-bar/)
  assert.match(source, /class="[^"]*active-action-rail/)
  assert.doesNotMatch(source, /class="record-progress-card"/)
  assert.doesNotMatch(source, /class="active-control-panel"/)
  assert.doesNotMatch(source, /class="active-echo-card"/)
  assert.doesNotMatch(source, /displayEchoNumericId/)
  assert.doesNotMatch(source, /副词条记录 \{\{ activeEcho\.substats\.length \}\}\/5/)
  assert.match(style, /\.active-summary \{[\s\S]+grid-template-columns: minmax\(280px, 300px\) minmax\(0, 1fr\);/)
  assert.match(style, /\.active-summary \{[\s\S]+align-items: stretch;/)
  assert.match(style, /\.active-echo-stage \{[\s\S]+min-height: 300px;/)
  assert.match(style, /\.active-record-panel \{[\s\S]+min-height: 300px;/)
  assert.match(style, /\.active-echo-stage \{[\s\S]+aspect-ratio: 1 \/ 1;/)
  assert.match(style, /\.active-echo-stage \{[\s\S]+width: 100%;/)
  assert.doesNotMatch(style, /\.active-echo-art-frame \{/)
  assert.match(style, /\.active-echo-stage-media \{[\s\S]+position: absolute;/)
  assert.match(style, /\.active-echo-set-badge \{[\s\S]+position: absolute;/)
  assert.match(style, /\.active-echo-stage-art \{[\s\S]+width: 100%;[\s\S]+height: 100%;[\s\S]+object-fit: cover;[\s\S]+transform: none;/)
  assert.match(style, /\.active-record-panel \{[\s\S]+display: grid;/)
  assert.match(style, /\.active-record-panel \{[\s\S]+grid-template-columns: minmax\(420px, 1fr\) 192px;/)
  assert.match(style, /\.active-record-main \{[\s\S]+grid-template-rows: auto minmax\(0, 1fr\);/)
  assert.match(style, /\.active-record-title-row \{[\s\S]+display: flex;/)
  assert.match(style, /\.active-echo-name-title \{[\s\S]+font-size: 28px;/)
  assert.match(style, /\.active-echo-name-title \{[\s\S]+font-weight: 760;[\s\S]+white-space: normal;/)
  assert.doesNotMatch(style, /\.active-title-compact/)
  assert.doesNotMatch(style, /\.active-title-stacked/)
  assert.doesNotMatch(style, /\.active-echo-name-title \{[^}]+text-overflow: ellipsis;/)
  assert.match(style, /\.active-record-count-badge \{[\s\S]+font-size: 18px;/)
  assert.match(style, /\.active-record-count-badge \{[\s\S]+font-variant-numeric: tabular-nums;/)
  assert.doesNotMatch(style, /\.active-echo-stage-cost \{/)
  assert.doesNotMatch(style, /\.active-echo-name-chip \{/)
  assert.match(style, /\.active-progress-segments \{[\s\S]+grid-template-columns: repeat\(5, minmax\(0, 1fr\)\);/)
  assert.match(style, /\.active-action-rail \{[\s\S]+border-left: 1px solid rgba\(216, 226, 234, 0\.72\);/)
})

test('active echo title keeps full names without hiding metadata pills', async () => {
  const source = await readFile(new URL('./ActiveEchoCapturePanel.vue', import.meta.url), 'utf8')
  const style = await readFile(new URL('../../styles/features/workspace-active.css', import.meta.url), 'utf8')

  assert.doesNotMatch(source, /const activeTitleCharacterCount = computed/)
  assert.doesNotMatch(source, /const activeRecordTitleClass = computed/)
  assert.doesNotMatch(source, /:class="activeRecordTitleClass"/)
  assert.match(style, /\.active-record-title-row \{[\s\S]+flex-direction: column;[\s\S]+flex-wrap: nowrap;/)
  assert.match(style, /\.active-echo-name-title \{[\s\S]+flex: 0 0 auto;[\s\S]+font-size: 28px;[\s\S]+font-weight: 760;[\s\S]+white-space: normal;/)
  assert.match(style, /\.active-record-meta-pills \{[\s\S]+flex: 0 1 auto;[\s\S]+flex-wrap: nowrap;[\s\S]+width: 100%;[\s\S]+min-width: 0;/)
  assert.match(style, /\.active-record-pill \{[\s\S]+flex: 0 1 auto;[\s\S]+min-width: 0;/)
  assert.doesNotMatch(style, /\.active-title-compact/)
  assert.doesNotMatch(style, /\.active-title-stacked/)
  assert.match(style, /@media \(max-width: 860px\) \{[\s\S]+\.active-record-title-row \{[\s\S]+flex-direction: column;/)
  assert.doesNotMatch(style, /\.active-echo-name-title \{[^}]+text-overflow: ellipsis;/)
})
test('active echo preview renders sharp artwork in a fixed-size stage', async () => {
  const source = await readFile(new URL('./ActiveEchoCapturePanel.vue', import.meta.url), 'utf8')
  const style = await readFile(new URL('../../styles/features/workspace-active.css', import.meta.url), 'utf8')

  assert.doesNotMatch(source, /active-echo-stage-vignette/)
  assert.doesNotMatch(style, /\.active-echo-stage-vignette/)
  assert.doesNotMatch(style, /filter:\s*blur\(/)
  assert.doesNotMatch(style, /filter:\s*drop-shadow\(/)
  assert.doesNotMatch(style, /box-shadow:\s*inset 0 -34px 42px/)
  assert.match(style, /\.active-summary \{[\s\S]+grid-template-columns: minmax\(280px, 300px\) minmax\(0, 1fr\);/)
  assert.match(style, /\.active-echo-stage \{[\s\S]+height: 300px;[\s\S]+aspect-ratio: 1 \/ 1;/)
  assert.match(style, /\.active-record-panel \{[\s\S]+height: 300px;/)
  assert.match(style, /\.active-echo-stage-media \{[\s\S]+width: 100%;[\s\S]+height: 100%;/)
  assert.match(style, /\.active-echo-stage-art \{[\s\S]+position: absolute;[\s\S]+inset: 0;[\s\S]+margin: auto;/)
  assert.match(style, /\.active-echo-stage-art \{[\s\S]+max-width: 100%;[\s\S]+max-height: 100%;[\s\S]+object-fit: cover;[\s\S]+transform: none;/)
  assert.match(style, /@media \(max-width: 860px\) \{[\s\S]+\.active-echo-stage \{[\s\S]+width: min\(100%, 300px\);[\s\S]+height: auto;[\s\S]+min-height: 0;[\s\S]+\}/)
  assert.match(style, /@media \(max-width: 860px\) \{[\s\S]+\.active-record-panel \{[\s\S]+height: auto;[\s\S]+\}/)
})

test('active echo carousel commits user preview selection directly', async () => {
  const source = await readFile(new URL('./ActiveEchoCapturePanel.vue', import.meta.url), 'utf8')

  assert.match(source, /function selectPreviewEcho\(index\) \{[\s\S]+activePreviewIndex\.value = index[\s\S]+emitPreviewEcho\(\)[\s\S]+\}/)
  assert.match(source, /function movePreviewEcho\(direction\) \{[\s\S]+selectPreviewEcho\(\(activePreviewIndex\.value \+ direction \+ total\) % total\)[\s\S]+\}/)
  assert.doesNotMatch(source, /watch\(\(\) => `\$\{previewSonataEffect\.value\?\.name/)
})

test('active echo console separates the ledger and uses one action rail button system', async () => {
  const source = await readFile(new URL('./ActiveEchoCapturePanel.vue', import.meta.url), 'utf8')
  const style = await readFile(new URL('../../styles/features/workspace-active.css', import.meta.url), 'utf8')

  assert.match(source, /import \{ formatPercent, formatSubstatTierValue \} from '\.\.\/\.\.\/services\/formatters'/)
  assert.doesNotMatch(source, /import tuningStatusIcon/)
  assert.doesNotMatch(source, /import undoActionIcon/)
  assert.doesNotMatch(source, /import trashIcon/)
  assert.doesNotMatch(source, /import arrowRightIcon/)
  assert.doesNotMatch(source, /function iconMask\(source\)/)
  assert.doesNotMatch(source, /const activeActionStatusLabel = computed/)
  assert.match(source, /predictionRankings:/)
  assert.match(source, /const activePredictionRankings = computed/)
  assert.match(source, /const activePredictionRecommendation = computed/)
  assert.match(source, /const activePredictionAlternatives = computed/)
  assert.match(source, /class="active-prediction-card"/)
  assert.match(source, /aria-label="下一个副词条预测"/)
  assert.doesNotMatch(source, /下条预测/)
  assert.match(source, /v-if="activePredictionRecommendation"/)
  assert.match(source, /class="active-prediction-table"/)
  assert.match(source, /class="active-prediction-subheading active-prediction-suggestion-heading">建议<\/span>/)
  assert.match(source, /class="active-prediction-line active-prediction-suggestion"/)
  assert.doesNotMatch(source, /active-prediction-tag/)
  assert.match(source, /class="active-prediction-subheading">备选<\/span>/)
  assert.match(source, /v-for="prediction in activePredictionAlternatives"/)
  assert.match(source, /class="active-prediction-line active-prediction-alternative"/)
  assert.match(source, /class="active-prediction-label"/)
  assert.match(source, /class="active-prediction-probability"/)
  assert.doesNotMatch(source, /active-prediction-rank/)
  assert.doesNotMatch(source, /`rank-\$\{prediction\.rank\}`/)
  assert.match(source, /formatPercent\(prediction\.probability, 1\)/)
  assert.match(source, /formatPercent\(activePredictionRecommendation\.probability, 1\)/)
  assert.match(source, /class="active-prediction-empty">等待预测<\/span>/)
  assert.doesNotMatch(source, /调谐中/)
  assert.match(source, /aria-label="撤回上一次录入的副词条"/)
  assert.match(source, /class="active-secondary-actions"/)
  assert.match(source, /class="active-action-button undo-action"/)
  assert.match(source, /<span>撤销<\/span>/)
  assert.doesNotMatch(source, /active-action-status/)
  assert.doesNotMatch(source, /class="ui-line-icon active-action-icon"/)
  assert.doesNotMatch(source, /icon-only-action/)
  assert.doesNotMatch(source, /<span>撤销上条<\/span>/)
  assert.match(source, /aria-label="弃置当前声骸"/)
  assert.match(source, /<span>弃置<\/span>/)
  assert.match(source, /aria-label="进入下一个声骸"/)
  assert.match(source, /<span>下一个<\/span>/)
  assert.doesNotMatch(source, /iconMask\(undoActionIcon\)/)
  assert.doesNotMatch(source, /iconMask\(trashIcon\)/)
  assert.doesNotMatch(source, /iconMask\(arrowRightIcon\)/)
  assert.match(source, /class="active-record-main"/)
  assert.match(source, /class="[^"]*active-action-rail/)
  assert.match(style, /\.active-record-panel \{[\s\S]+grid-template-columns: minmax\(420px, 1fr\) 192px;/)
  assert.match(style, /\.active-record-main \{[\s\S]+display: grid;[\s\S]+grid-template-rows: auto minmax\(0, 1fr\);/)
  assert.match(style, /\.active-action-button \{[\s\S]+font-size: 14px;[\s\S]+font-weight: 700;/)
  assert.match(style, /\.active-record-panel \{[\s\S]+display: grid;/)
  assert.match(style, /\.active-record-panel \{[\s\S]+overflow: hidden;/)
  assert.match(style, /\.active-actions \{[\s\S]+grid-template-columns: 1fr;[\s\S]+align-self: stretch;/)
  assert.match(style, /\.active-action-rail \{[\s\S]+display: grid;[\s\S]+grid-template-rows: auto auto auto;[\s\S]+align-content: center;[\s\S]+border-left: 1px solid rgba\(216, 226, 234, 0\.72\);[\s\S]+padding: 14px 14px 16px;/)
  assert.match(style, /\.active-secondary-actions \{[\s\S]+grid-template-columns: repeat\(2, minmax\(0, 1fr\)\);/)
  assert.doesNotMatch(style, /\.active-action-status \{/)
  assert.doesNotMatch(style, /\.active-action-anchor \{/)
  assert.match(style, /\.active-prediction-card \{[\s\S]+display: grid;[\s\S]+align-content: center;[\s\S]+min-height: 144px;[\s\S]+background: #f7f9fb;/)
  assert.doesNotMatch(style, /\.active-prediction-heading/)
  assert.match(style, /\.active-prediction-table \{[\s\S]+gap: 5px;/)
  assert.match(style, /\.active-prediction-line \{[\s\S]+grid-template-columns: minmax\(max-content, 1fr\) max-content;[\s\S]+gap: 6px;[\s\S]+border: 1px solid transparent;[\s\S]+border-radius: 10px;[\s\S]+padding: 5px 6px;/)
  assert.match(style, /\.active-prediction-suggestion \{[\s\S]+border-color: rgba\(44, 159, 112, 0\.12\);[\s\S]+background: rgba\(44, 159, 112, 0\.1\);/)
  assert.doesNotMatch(style, /\.active-prediction-suggestion \{[^}]+margin: 0 -/)
  assert.doesNotMatch(style, /\.active-prediction-suggestion \{[^}]+grid-template-columns: auto/)
  assert.doesNotMatch(style, /\.active-prediction-tag/)
  assert.match(style, /\.active-prediction-subheading \{[\s\S]+font-size: 11px;/)
  assert.match(style, /\.active-prediction-suggestion-heading \{[\s\S]+color: #2c7a59;/)
  assert.match(style, /\.active-prediction-alternative \{[\s\S]+border-color: transparent;[\s\S]+background: transparent;/)
  assert.match(style, /\.active-prediction-label \{[\s\S]+min-width: max-content;[\s\S]+overflow-wrap: normal;[\s\S]+white-space: nowrap;[\s\S]+word-break: keep-all;/)
  assert.match(style, /\.active-prediction-probability \{[\s\S]+min-width: max-content;/)
  assert.doesNotMatch(style, /\.active-prediction-label \{[^}]+white-space: normal;/)
  assert.doesNotMatch(style, /\.active-prediction-label \{[^}]+text-overflow: ellipsis;/)
  assert.doesNotMatch(style, /\.active-prediction-label \{[^}]+overflow: hidden;/)
  assert.match(style, /\.active-prediction-probability \{[\s\S]+font-variant-numeric: tabular-nums;/)
  assert.doesNotMatch(style, /\.active-prediction-rank/)
  assert.doesNotMatch(style, /\.active-prediction-line\.rank-/)
  assert.match(style, /\.active-action-button \{[\s\S]+width: 100%;[\s\S]+min-height: 40px;[\s\S]+border-radius: 12px;/)
  assert.match(style, /\.next-action \{[\s\S]+min-height: 46px;/)
  assert.doesNotMatch(style, /\.icon-only-action \{/)
  assert.doesNotMatch(style, /\.discard-action \{[^}]+min-height:/)
  assert.match(style, /\.roll-strip \{[\s\S]+grid-template-rows: repeat\(5, minmax\(0, 1fr\)\);/)
  assert.match(style, /\.roll-strip span \{[\s\S]+grid-template-columns: 24px minmax\(0, 1fr\) 76px;/)
  assert.match(style, /\.roll-value \{[\s\S]+justify-self: end;[\s\S]+min-width: 76px;[\s\S]+text-align: right;/)
  assert.match(style, /\.record-actions \{[\s\S]+align-self: stretch;[\s\S]+margin-top: 0;/)
  assert.match(style, /@media \(max-width: 860px\) \{[\s\S]+\.active-action-rail \{[\s\S]+grid-template-columns: repeat\(3, minmax\(0, 1fr\)\);/)
  assert.match(style, /@media \(max-width: 860px\) \{[\s\S]+\.active-secondary-actions \{ display: contents; \}/)
  assert.doesNotMatch(style, /\.active-action-button \.active-action-icon/)
})

test('dark active echo actions use a single tonal hierarchy', async () => {
  const style = await readFile(new URL('../../styles/features/workspace.css', import.meta.url), 'utf8')

  assert.match(style, /\.app-shell\.theme-dark \.undo-action \{[\s\S]+border-color: #31485c;[\s\S]+color: #c8d5df;[\s\S]+background: #101b23;/)
  assert.match(style, /\.app-shell\.theme-dark \.undo-action:hover:not\(:disabled\) \{[\s\S]+border-color: #4b78a1;[\s\S]+color: #e8f3ff;[\s\S]+background: #152839;/)
  assert.match(style, /\.app-shell\.theme-dark \.discard-action \{[\s\S]+border-color: #5c3440;[\s\S]+color: #ff9aaa;[\s\S]+background: #101b23;/)
  assert.match(style, /\.app-shell\.theme-dark \.discard-action:hover:not\(:disabled\) \{[\s\S]+border-color: #9b4a5b;[\s\S]+color: #ffd4db;[\s\S]+background: #2a1b23;/)
  assert.match(style, /\.app-shell\.theme-dark \.next-action \{[\s\S]+border-color: #2361b7;[\s\S]+color: #ffffff;[\s\S]+background: #2361b7;/)
  assert.match(style, /\.app-shell\.theme-dark \.next-action:hover:not\(:disabled\) \{[\s\S]+border-color: #2a73d1;[\s\S]+background: #2a73d1;/)
})

test('echo workbench keeps tier values calm and probabilities secondary', async () => {
  const source = await readFile(new URL('./EchoWorkbenchView.vue', import.meta.url), 'utf8')
  const style = await readFile(new URL('../../styles/features/workspace.css', import.meta.url), 'utf8')

  assert.match(source, /formatSubstatTierNumber/)
  assert.match(source, /formatSubstatTierUnit/)
  assert.match(source, /class="tier-value"/)
  assert.match(source, /class="tier-unit"/)
  assert.match(source, /class="tier-probability"/)
  assert.match(source, /formatPercent\(tier\.probability, 1\)/)
  assert.match(style, /\.tier-grid button \{[\s\S]+padding: 5px 10px;/)
  assert.match(style, /\.tier-value \{[\s\S]+font-size: 17px; font-weight: 700;/)
  assert.match(style, /\.tier-unit \{[\s\S]+font-size: 0\.72em;/)
  assert.match(style, /\.tier-probability \{[\s\S]+font-size: 11px; font-weight: 400;/)
  assert.match(style, /\.tier-probability \{[\s\S]+font-variant-numeric: tabular-nums;/)
})

test('workspace styles keep long substat titles and recorded rows stable', async () => {
  const source = await readFile(new URL('./EchoWorkbenchView.vue', import.meta.url), 'utf8')
  const style = [
    await readFile(new URL('../../styles/features/workspace.css', import.meta.url), 'utf8'),
    await readFile(new URL('../../styles/features/workspace-active.css', import.meta.url), 'utf8'),
  ].join('\n')
  const topPredictedIcon = await readFile(new URL('../../assets/icons/fast-arrow-up.svg', import.meta.url), 'utf8')

  assert.match(source, /class="substat-title-line"/)
  assert.match(source, /import topPredictedIcon from '\.\.\/\.\.\/assets\/icons\/fast-arrow-up\.svg'/)
  assert.match(source, /class="top-predicted-indicator"/)
  assert.match(source, /aria-label="预测概率提升"/)
  assert.match(source, /class="ui-line-icon top-predicted-icon"/)
  assert.doesNotMatch(source, />预测最高<\/span>/)
  assert.match(style, /\.substat-title-line \{[\s\S]+grid-template-columns: minmax\(0, 1fr\) auto;/)
  assert.match(style, /\.top-predicted-indicator \{[\s\S]+width: 24px; height: 24px;/)
  assert.match(style, /\.top-predicted-icon \{[\s\S]+width: 14px; height: 14px;/)
  assert.match(topPredictedIcon, /M6 11L12 5L18 11/)
  assert.match(topPredictedIcon, /M6 19L12 13L18 19/)
  assert.doesNotMatch(topPredictedIcon, /a2 2 0 0 0/)
  assert.match(style, /\.substat-row \{[\s\S]+min-height: 70px;/)
  assert.doesNotMatch(style, /\.matrix-guide \{/)
  assert.match(style, /\.active-summary \{[\s\S]+grid-template-columns: minmax\(280px, 300px\) minmax\(0, 1fr\);/)
  assert.match(style, /\.active-summary \{[\s\S]+align-items: stretch;/)
  assert.match(style, /\.active-record-panel \{[\s\S]+grid-template-columns: minmax\(420px, 1fr\) 192px;/)
  assert.match(style, /\.active-record-main \{[\s\S]+grid-template-rows: auto minmax\(0, 1fr\);/)
  assert.match(style, /\.record-actions \{[\s\S]+align-self: stretch;[\s\S]+margin-top: 0;/)
  assert.doesNotMatch(style, /\.active-action-status \{/)
  assert.match(style, /\.app-shell\.theme-dark \.active-prediction-card \{[\s\S]+background: #14212b;/)
  assert.match(style, /\.app-shell\.theme-dark \.active-prediction-suggestion \{[\s\S]+background: rgba\(55, 179, 127, 0\.14\);/)
  assert.match(style, /\.app-shell\.theme-dark \.active-prediction-suggestion-heading \{[\s\S]+color: #9ed9b8;/)
  assert.doesNotMatch(style, /\.app-shell\.theme-dark \.active-prediction-tag/)
  assert.match(style, /\.app-shell\.theme-dark \.active-prediction-alternative \{[\s\S]+color: #b5c8bb;/)
  assert.doesNotMatch(style, /\.app-shell\.theme-dark \.active-prediction-line\.rank-/)
  assert.doesNotMatch(style, /\.active-control-panel \{/)
  assert.match(style, /\.roll-strip span \{[\s\S]+grid-template-columns: 24px minmax\(0, 1fr\) 76px;/)
  assert.match(style, /\.roll-slot \{[\s\S]+min-height: 36px;/)
  assert.match(style, /\.roll-slot\.pending \{[\s\S]+color: var\(--steel\);/)
  assert.match(style, /\.substat-meta \{[\s\S]+min-height: 46px;/)
  assert.match(style, /\.substat-row\.top-predicted-row \{[\s\S]+box-shadow: inset 4px 0 0 rgba\(44, 159, 112, 0\.62\);/)
  assert.match(style, /\.substat-row\.recorded \{[\s\S]+box-shadow: inset 4px 0 0 rgba\(23, 105, 210, 0\.42\);/)
})

test('echo setup keeps main stat changes compact and softly animated', async () => {
  const source = await readFile(new URL('./EchoWorkbenchView.vue', import.meta.url), 'utf8')
  const layoutSource = await readFile(new URL('./useEchoWorkbenchLayout.js', import.meta.url), 'utf8')
  const style = await readFile(new URL('../../styles/features/workspace.css', import.meta.url), 'utf8')

  assert.match(source, /import \{ useEchoWorkbenchLayout \} from '\.\/useEchoWorkbenchLayout'/)
  assert.match(layoutSource, /const mainStatRowRef = ref\(null\)/)
  assert.match(layoutSource, /const mainStatRowStyle = computed/)
  assert.match(layoutSource, /function clearMainStatRowHeight/)
  assert.match(layoutSource, /async function animateMainStatRowChange/)
  assert.match(layoutSource, /legalMainStats\.value\.join\('\|'\)/)
  assert.match(layoutSource, /function measureMainStatRowContentHeight/)
  assert.match(layoutSource, /mainStatRowRef\.value\.firstElementChild/)
  assert.doesNotMatch(layoutSource, /row\.scrollHeight/)
  assert.match(source, /<div\s+ref="mainStatRowRef"\s+class="main-stat-row-shell"\s+:style="mainStatRowStyle"\s+@transitionend="clearMainStatRowHeight"\s*>/)
  assert.match(source, /<TransitionGroup name="main-stat-option" tag="div" class="option-row main-stat-row">/)
  assert.match(style, /\.main-stat-row-shell \{[\s\S]+transition: height 160ms ease-out;/)
  assert.match(style, /\.main-stat-row \{[\s\S]+align-content: start;/)
  assert.doesNotMatch(style, /\.main-stat-row \{[\s\S]+min-height: 148px;/)
  assert.match(style, /\.main-stat-option-move,\s+\.main-stat-option-enter-active,\s+\.main-stat-option-leave-active \{[\s\S]+transition: opacity 140ms ease-out, transform 140ms ease-out;/)
  assert.match(style, /\.main-stat-option-enter-from,\s+\.main-stat-option-leave-to \{[\s\S]+opacity: 0;/)
})

test('echo workbench emits commands without owning persistence', async () => {
  const source = await readFile(new URL('./EchoWorkbenchView.vue', import.meta.url), 'utf8')

  assert.match(source, /defineEmits\(\['config-change', 'undo', 'discard', 'next', 'select-tier', 'preview-change'\]\)/)
  assert.match(source, /emit\('config-change', \{ sonata: effect\.name \}\)/)
  assert.match(source, /emit\('select-tier', \{ row, tier \}\)/)
  assert.doesNotMatch(source, /from '\.\.\/\.\.\/services\/api'/)
})

test('echo workbench scopes pending tier memoization to the active substat row', async () => {
  const source = await readFile(new URL('./EchoWorkbenchView.vue', import.meta.url), 'utf8')

  assert.match(source, /function rowPendingTierKey\(row\)/)
  assert.match(source, /props\.pendingTierKey\.startsWith\(`\$\{row\.substat_type\}:`\)/)
  assert.match(source, /v-memo="\[row\.recorded\?\.id, row\.recorded\?\.tier_value, row\.candidate\?\.p_final, row\.candidate\?\.baseline_deviation, row\.topPredicted, rowPendingTierKey\(row\)\]"/)
  assert.doesNotMatch(source, /row\.topPredicted, pendingTierKey\]/)
})

test('echo workbench disables costs unavailable for the selected sonata', async () => {
  const source = await readFile(new URL('./EchoWorkbenchView.vue', import.meta.url), 'utf8')
  const style = await readFile(new URL('../../styles/features/workspace.css', import.meta.url), 'utf8')

  assert.match(source, /const costOptions = Object\.freeze\(\[1, 3, 4\]\)/)
  assert.match(source, /const selectedSonataEffect = computed/)
  assert.match(source, /const availableCosts = computed/)
  assert.match(source, /function isCostAvailable\(cost\)/)
  assert.match(source, /function selectCost\(cost\)/)
  assert.match(source, /v-for="cost in costOptions"/)
  assert.match(source, /:disabled="!isCostAvailable\(cost\)"/)
  assert.match(source, /@click="selectCost\(cost\)"/)
  assert.match(style, /\.option-row button:disabled \{[\s\S]+opacity: 0\.46;/)
  assert.match(style, /\.app-shell\.theme-dark \.option-row button:disabled \{[\s\S]+background: #17232d;/)
})

test('echo workbench owns setup panel height synchronization', async () => {
  const source = await readFile(new URL('./useEchoWorkbenchLayout.js', import.meta.url), 'utf8')

  assert.match(source, /const createPanelRef = ref\(null\)/)
  assert.match(source, /const galleryPanelRef = ref\(null\)/)
  assert.match(source, /const sonataGridRef = ref\(null\)/)
  assert.match(source, /async function focusActiveSonata/)
  assert.match(source, /querySelector\('button\.active'\)/)
  assert.match(source, /export function sonataScrollTopForActiveButton/)
  assert.match(source, /grid\.scrollTop = sonataScrollTopForActiveButton\(grid, activeButton\)/)
  assert.match(source, /async function syncSetupPanelLayout\(\) \{[\s\S]+await syncSetupPanelHeight\(\)[\s\S]+await focusActiveSonata\(\)[\s\S]+\}/)
  assert.match(source, /window\.addEventListener\('resize', syncSetupPanelLayout\)/)
  assert.match(source, /window\.removeEventListener\('resize', syncSetupPanelLayout\)/)
  assert.match(source, /syncSetupPanelLayout,\s+\{ flush: 'post' \}/)
  assert.match(source, /\(\) => `\$\{props\.activeEcho\?\.id \|\| ''\}:\$\{props\.config\.cost\}:\$\{props\.config\.main_stat\}:\$\{props\.config\.sonata\}`/)
  assert.doesNotMatch(source, /substats\.length/)
})
