import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

test('echo workbench owns setup and active echo presentation', async () => {
  const source = await readFile(new URL('./EchoWorkbenchView.vue', import.meta.url), 'utf8')
  const captureSource = await readFile(new URL('./ActiveEchoCapturePanel.vue', import.meta.url), 'utf8')

  assert.match(source, /import \{ sonataEffects \} from '\.\.\/\.\.\/data\/sonataEffects'/)
  assert.match(source, /import \{ mainStatLabels, mainStatsByCost \} from '\.\.\/\.\.\/data\/substats'/)
  assert.match(source, /import ActiveEchoCapturePanel from '\.\/ActiveEchoCapturePanel\.vue'/)
  assert.match(source, /const legalMainStats = computed\(\(\) => mainStatsByCost\[props\.config\.cost\] \|\| \[\]\)/)
  assert.match(source, /const predictionRankings = computed/)
  assert.match(source, /Number\.isFinite\(row\.candidate\?\.p_final\)/)
  assert.match(source, /probability: row\.candidate\.p_final/)
  assert.match(captureSource, /const activeEchoDisplayName = computed/)
  assert.match(source, /:prediction-rankings="predictionRankings"/)
  assert.match(source, /class="product-panel create-panel"/)
  assert.match(source, /class="gallery-panel"/)
  assert.match(source, /ref="sonataGridRef"/)
  assert.match(source, /:aria-current="config\.sonata === effect\.name \? 'true' : null"/)
  assert.match(source, />ECHO SETUP</)
  assert.match(source, /选择套装、COST、主词条后开始录入。/)
  assert.match(captureSource, /activeSonataEffect/)
  assert.match(captureSource, /class="active-echo-stage"/)
  assert.match(captureSource, /class="active-echo-set-badge"/)
  assert.match(captureSource, /class="active-record-panel"/)
  assert.match(captureSource, /class="active-echo-name-title"/)
  assert.match(captureSource, /class="active-record-meta-pills"/)
  assert.doesNotMatch(captureSource, /displayEchoNumericId/)
  assert.doesNotMatch(source, /<span>当前声骸<\/span>/)
  assert.doesNotMatch(source, /<h3 class="active-section-title">当前声骸<\/h3>/)
  assert.doesNotMatch(source, /class="setup-current-summary"/)
  assert.doesNotMatch(source, /class="active-config-chips"/)
  assert.doesNotMatch(source, /class="matrix-guide"/)
})

test('echo setup defaults to continuous tuning without exposing a mode switch', async () => {
  const source = await readFile(new URL('./EchoWorkbenchView.vue', import.meta.url), 'utf8')
  const workflowSource = await readFile(new URL('./useEchoWorkspace.js', import.meta.url), 'utf8')

  assert.doesNotMatch(source, /同一批连续调谐/)
  assert.doesNotMatch(source, /type="checkbox"/)
  assert.doesNotMatch(source, /is_continuous_tuning: \$event\.target\.checked/)
  assert.match(workflowSource, /is_continuous_tuning: true/)
})

test('echo setup filters sonata options and explains immediate creation', async () => {
  const source = await readFile(new URL('./EchoWorkbenchView.vue', import.meta.url), 'utf8')
  const searchSource = await readFile(new URL('./SonataSearchField.vue', import.meta.url), 'utf8').catch(() => '')
  const style = await readFile(new URL('../../styles/features/workspace-search.css', import.meta.url), 'utf8')

  assert.match(source, /const sonataQuery = ref\(''\)/)
  assert.match(source, /filterSonataEffects\(sonataEffects, sonataQuery\.value\)/)
  assert.match(source, /useEchoWorkbenchLayout\(props, legalMainStats, visibleSonataNames\)/)
  assert.match(source, /import SonataSearchField from '\.\/SonataSearchField\.vue'/)
  assert.match(source, /<SonataSearchField v-model="sonataQuery" \/>/)
  assert.match(searchSource, /const query = defineModel/)
  assert.match(searchSource, /import searchIcon from '\.\.\/\.\.\/assets\/icons\/search\.svg'/)
  assert.match(searchSource, /import clearIcon from '\.\.\/\.\.\/assets\/icons\/x\.svg'/)
  assert.match(searchSource, /class="sonata-search-field" role="search"/)
  assert.match(searchSource, /class="ui-line-icon sonata-search-icon"[\s\S]+iconMask\(searchIcon\)/)
  assert.match(searchSource, /type="search"[\s\S]+aria-label="筛选套装"[\s\S]+placeholder="输入名称筛选"/)
  assert.match(searchSource, /v-if="query"[\s\S]+class="sonata-search-clear"[\s\S]+aria-label="清除套装筛选"[\s\S]+@click="query = ''"/)
  assert.match(searchSource, /class="ui-line-icon sonata-search-clear-icon"[\s\S]+iconMask\(clearIcon\)/)
  assert.doesNotMatch(searchSource, /class="sr-only"/)
  assert.match(style, /\.sonata-search-field \{[\s\S]+margin: 0 14px 12px 0;/)
  assert.match(style, /\.sonata-search-field input \{[\s\S]+min-height: 44px;[\s\S]+padding: 10px 40px 10px 38px;/)
  assert.match(style, /\.sonata-search-field input::placeholder \{[\s\S]+color: var\(--steel\);[\s\S]+opacity: 1;/)
  assert.match(style, /\.sonata-search-icon \{[\s\S]+color: var\(--steel\);/)
  assert.match(style, /\.sonata-search-clear \{[\s\S]+width: 32px;[\s\S]+height: 32px;/)
  assert.match(source, /v-for="effect in filteredSonataEffects"/)
  assert.match(source, /未找到匹配套装/)
  assert.match(source, /选择其他配置将新建声骸/)
  assert.match(source, /role="status" aria-live="polite"/)
})

test('echo workbench keeps substat rows focused on entry by default', async () => {
  const source = await readFile(new URL('./EchoWorkbenchView.vue', import.meta.url), 'utf8')
  const captureSource = await readFile(new URL('./ActiveEchoCapturePanel.vue', import.meta.url), 'utf8')
  const combinedSource = `${source}\n${captureSource}`

  assert.match(combinedSource, /formatSubstatTierValue/)
  assert.match(captureSource, /class="roll-position"/)
  assert.match(captureSource, /class="roll-name"/)
  assert.match(captureSource, /class="roll-value"/)
  assert.match(captureSource, /class="active-record-head"/)
  assert.match(captureSource, /class="active-record-count-badge"/)
  assert.match(captureSource, /const rollSlots = computed/)
  assert.match(captureSource, /Array\.from\(\{ length: 5 \}/)
  assert.match(captureSource, /<strong class="active-record-count-badge"><span>\{\{ activeEchoSubstats\.length \}\}<\/span><small>\/5<\/small><\/strong>/)
  assert.match(captureSource, /待调谐/)
  assert.match(captureSource, /<b class="roll-value">\{\{ formatSubstatTierValue\(roll\.substat_type, roll\.tier_value\) \}\}<\/b>/)
  assert.match(source, /{{ formatSubstatTierValue\(row\.substat_type, row\.recorded\.tier_value\) }}/)
  assert.match(source, /formatSubstatTierNumber\(row\.substat_type, tier\.value\)/)
  assert.doesNotMatch(source, /副词条记录 \{\{ activeEcho\.substats\.length \}\}\/5/)
  assert.match(captureSource, /activeRecordPills/)
  assert.match(captureSource, /const activeRecordPills = computed\(\(\) => \[\s+props\.activeEcho\?\.set_name \|\| props\.config\.sonata,\s+`COST \$\{previewCost\.value\}`,/)
  assert.match(captureSource, /mainStatLabels\[props\.activeEcho\?\.main_stat \|\| props\.config\.main_stat\]/)
  assert.doesNotMatch(source, /formatPercent\(row\.candidate\.p_final\)/)
  assert.doesNotMatch(source, /formatSignedPercent\(row\.candidate\.baseline_deviation\)/)
  assert.doesNotMatch(source, /<small v-if="row\.candidate">/)
})

test('active echo area uses an immersive preview and record console', async () => {
  const source = await readFile(new URL('./ActiveEchoCapturePanel.vue', import.meta.url), 'utf8')
  const style = await readFile(new URL('../../styles/features/workspace-active.css', import.meta.url), 'utf8')
  const baseTitleRule = style.match(/^\.active-echo-name-title \{[^}]+\}/m)?.[0] || ''

  assert.match(source, /import \{ sonataEchoesBySetName \} from '\.\.\/\.\.\/data\/sonataEchoes'/)
  assert.match(source, /const activeEchoesForCost = computed/)
  assert.match(source, /const activePreviewEcho = computed/)
  assert.match(source, /class="active-echo-stage"/)
  assert.match(source, /class="active-echo-stage-media"/)
  assert.match(source, /class="active-echo-set-badge"/)
  assert.match(source, /class="active-echo-stage-art"/)
  assert.doesNotMatch(source, /class="active-echo-art-frame"/)
  assert.doesNotMatch(source, /class="active-echo-stage-cost"/)
  assert.doesNotMatch(source, /class="active-echo-name-chip"/)
  assert.match(source, /class="active-record-panel"/)
  assert.match(source, /class="active-record-main"/)
  assert.match(source, /class="active-echo-name-title"/)
  assert.match(source, /class="active-record-meta-pills"/)
  assert.match(source, /class="active-record-pill"/)
  assert.match(source, /class="active-record-count-badge"/)
  assert.match(source, /const activeEchoSubstats = computed/)
  assert.match(source, /const progressSegments = computed/)
  assert.match(source, /current: index === activeEchoSubstats\.value\.length/)
  assert.match(source, /class="active-progress-row"/)
  assert.match(source, /class="active-progress-segments"/)
  assert.match(source, /class="roll-slot"/)
  assert.match(source, /:class="\{ pending: roll\.pending, current: roll\.current \}"/)
  assert.match(source, /:aria-current="roll\.current \? 'step' : null"/)
  assert.match(source, /<div class="active-progress-row">[\s\S]+class="active-progress-segments"[\s\S]+<strong class="active-record-count-badge"><span>\{\{ activeEchoSubstats\.length \}\}<\/span><small>\/5<\/small><\/strong>[\s\S]+<\/div>/)
  assert.doesNotMatch(source, /activeEcho\?\.substats\.length/)
  assert.match(source, /class="[^"]*record-actions/)
  assert.match(source, /class="[^"]*active-action-bar/)
  assert.match(source, /class="[^"]*active-action-rail/)
  assert.doesNotMatch(source, /class="record-progress-card"/)
  assert.doesNotMatch(source, /class="active-control-panel"/)
  assert.doesNotMatch(source, /class="active-echo-card"/)
  assert.doesNotMatch(source, /displayEchoNumericId/)
  assert.doesNotMatch(source, /副词条记录 \{\{ activeEcho\.substats\.length \}\}\/5/)
  assert.match(style, /\.active-summary \{[\s\S]+grid-template-columns: minmax\(280px, 300px\) minmax\(0, 1fr\);/)
  assert.match(style, /\.active-summary \{[\s\S]+align-items: stretch;/)
  assert.match(style, /\.active-echo-stage \{[\s\S]+min-height: 300px;/)
  assert.match(style, /\.active-record-panel \{[\s\S]+min-height: 300px;/)
  assert.match(style, /\.active-echo-stage \{[\s\S]+aspect-ratio: 1 \/ 1;/)
  assert.match(style, /\.active-echo-stage \{[\s\S]+width: 100%;/)
  assert.doesNotMatch(style, /\.active-echo-art-frame \{/)
  assert.match(style, /\.active-echo-stage-media \{[\s\S]+position: absolute;/)
  assert.match(style, /\.active-echo-set-badge \{[\s\S]+position: absolute;/)
  assert.match(style, /\.active-echo-stage-art \{[\s\S]+width: 100%;[\s\S]+height: 100%;[\s\S]+object-fit: cover;[\s\S]+transform: none;/)
  assert.match(style, /\.active-record-panel \{[\s\S]+display: grid;/)
  assert.match(style, /\.active-record-panel \{[\s\S]+grid-template-columns: minmax\(0, 1fr\) clamp\(232px, 30%, 248px\);/)
  assert.match(style, /\.active-record-main \{[\s\S]+grid-template-rows: auto minmax\(0, 1fr\);/)
  assert.match(style, /\.active-record-title-row \{[\s\S]+display: flex;/)
  assert.match(style, /\.active-echo-name-title \{[\s\S]+font-size: var\(--text-page-title\);/)
  assert.match(style, /\.active-echo-name-title \{[\s\S]+font-weight: var\(--weight-title\);[\s\S]+white-space: normal;/)
  assert.doesNotMatch(style, /\.active-title-compact/)
  assert.doesNotMatch(style, /\.active-title-stacked/)
  assert.doesNotMatch(baseTitleRule, /text-overflow: ellipsis;/)
  assert.match(style, /\.active-record-head \{[\s\S]+grid-template-columns: minmax\(0, 1fr\);/)
  assert.match(style, /\.active-progress-row \{[\s\S]+grid-template-columns: minmax\(0, 1fr\) auto;/)
  assert.match(style, /\.active-record-count-badge \{[\s\S]+border: 0;[\s\S]+padding: 0;[\s\S]+background: transparent;[\s\S]+font-size: var\(--text-data-sm\);/)
  assert.match(style, /\.active-record-count-badge \{[\s\S]+font-variant-numeric: tabular-nums;/)
  assert.doesNotMatch(style, /\.active-echo-stage-cost \{/)
  assert.doesNotMatch(style, /\.active-echo-name-chip \{/)
  assert.match(style, /\.active-progress-segments \{[\s\S]+grid-template-columns: repeat\(5, minmax\(0, 1fr\)\);/)
  assert.match(style, /\.roll-slot\.pending\.current \{[\s\S]+color: var\(--ink\);[\s\S]+background: rgba\(0, 100, 224, 0\.06\);/)
  assert.match(style, /\.active-action-rail \{[\s\S]+border-left: 1px solid rgba\(216, 226, 234, 0\.72\);[\s\S]+padding: 16px;[\s\S]+background: #f7f9fb;/)
})

test('active echo title keeps full names without hiding metadata pills', async () => {
  const source = await readFile(new URL('./ActiveEchoCapturePanel.vue', import.meta.url), 'utf8')
  const style = await readFile(new URL('../../styles/features/workspace-active.css', import.meta.url), 'utf8')
  const baseTitleRule = style.match(/^\.active-echo-name-title \{[^}]+\}/m)?.[0] || ''

  assert.doesNotMatch(source, /const activeTitleCharacterCount = computed/)
  assert.doesNotMatch(source, /const activeRecordTitleClass = computed/)
  assert.doesNotMatch(source, /:class="activeRecordTitleClass"/)
  assert.match(style, /\.active-record-title-row \{[\s\S]+flex-direction: column;[\s\S]+flex-wrap: nowrap;/)
  assert.match(style, /\.active-echo-name-title \{[\s\S]+flex: 0 0 auto;[\s\S]+font-size: var\(--text-page-title\);[\s\S]+font-weight: var\(--weight-title\);[\s\S]+white-space: normal;/)
  assert.match(style, /\.active-record-meta-pills \{[\s\S]+flex: 0 1 auto;[\s\S]+flex-wrap: nowrap;[\s\S]+width: 100%;[\s\S]+min-width: 0;/)
  assert.match(style, /\.active-record-pill \{[\s\S]+flex: 0 1 auto;[\s\S]+min-width: 0;/)
  assert.doesNotMatch(style, /\.active-title-compact/)
  assert.doesNotMatch(style, /\.active-title-stacked/)
  assert.match(style, /@media \(max-width: 860px\) \{[\s\S]+\.active-record-title-row \{[\s\S]+flex-direction: column;/)
  assert.doesNotMatch(baseTitleRule, /text-overflow: ellipsis;/)
})
test('active echo preview renders sharp artwork in a fixed-size stage', async () => {
  const source = await readFile(new URL('./ActiveEchoCapturePanel.vue', import.meta.url), 'utf8')
  const style = await readFile(new URL('../../styles/features/workspace-active.css', import.meta.url), 'utf8')

  assert.doesNotMatch(source, /active-echo-stage-vignette/)
  assert.doesNotMatch(style, /\.active-echo-stage-vignette/)
  assert.doesNotMatch(style, /filter:\s*blur\(/)
  assert.doesNotMatch(style, /filter:\s*drop-shadow\(/)
  assert.doesNotMatch(style, /box-shadow:\s*inset 0 -34px 42px/)
  assert.match(style, /\.active-summary \{[\s\S]+grid-template-columns: minmax\(280px, 300px\) minmax\(0, 1fr\);/)
  assert.match(style, /\.active-echo-stage \{[\s\S]+height: 300px;[\s\S]+aspect-ratio: 1 \/ 1;/)
  assert.match(style, /\.active-record-panel \{[\s\S]+height: 300px;/)
  assert.match(style, /\.active-echo-stage-media \{[\s\S]+width: 100%;[\s\S]+height: 100%;/)
  assert.match(style, /\.active-echo-stage-art \{[\s\S]+position: absolute;[\s\S]+inset: 0;[\s\S]+margin: auto;/)
  assert.match(style, /\.active-echo-stage-art \{[\s\S]+max-width: 100%;[\s\S]+max-height: 100%;[\s\S]+object-fit: cover;[\s\S]+transform: none;/)
  assert.match(style, /@media \(max-width: 860px\) \{[\s\S]+\.active-echo-stage \{[\s\S]+width: min\(100%, 300px\);[\s\S]+height: auto;[\s\S]+min-height: 0;[\s\S]+\}/)
  assert.match(style, /@media \(max-width: 860px\) \{[\s\S]+\.active-record-panel \{[\s\S]+height: auto;[\s\S]+\}/)
})

test('active echo carousel commits user preview selection directly', async () => {
  const source = await readFile(new URL('./ActiveEchoCapturePanel.vue', import.meta.url), 'utf8')

  assert.match(source, /function selectPreviewEcho\(index\) \{[\s\S]+activePreviewIndex\.value = index[\s\S]+emitPreviewEcho\(\)[\s\S]+\}/)
  assert.match(source, /function movePreviewEcho\(direction\) \{[\s\S]+selectPreviewEcho\(\(activePreviewIndex\.value \+ direction \+ total\) % total\)[\s\S]+\}/)
  assert.doesNotMatch(source, /watch\(\(\) => `\$\{previewSonataEffect\.value\?\.name/)
})

test('active echo console separates the ledger and uses one action rail button system', async () => {
  const source = await readFile(new URL('./ActiveEchoCapturePanel.vue', import.meta.url), 'utf8')
  const style = await readFile(new URL('../../styles/features/workspace-active.css', import.meta.url), 'utf8')

  assert.match(source, /import \{ formatPercent, formatSubstatTierValue \} from '\.\.\/\.\.\/services\/formatters'/)
  assert.doesNotMatch(source, /import tuningStatusIcon/)
  assert.match(source, /import undoActionIcon from '\.\.\/\.\.\/assets\/icons\/undo-action\.svg'/)
  assert.match(source, /import trashIcon from '\.\.\/\.\.\/assets\/icons\/trash\.svg'/)
  assert.doesNotMatch(source, /import arrowRightIcon/)
  assert.match(source, /function iconMask\(source\)/)
  assert.doesNotMatch(source, /const activeActionStatusLabel = computed/)
  assert.match(source, /predictionRankings:/)
  assert.match(source, /const activePredictionRankings = computed/)
  assert.match(source, /function predictionDisplayBucket\(probability\)/)
  assert.match(source, /Math\.round\(probability \* 1000\)/)
  assert.match(source, /const activePredictionTopBucket = computed/)
  assert.match(source, /const activePredictionRecommendations = computed/)
  assert.match(source, /const activePredictionAlternatives = computed/)
  assert.match(source, /class="active-prediction-card"/)
  assert.match(source, /aria-label="下一个副词条预测"/)
  assert.doesNotMatch(source, /下条预测/)
  assert.match(source, /v-if="activePredictionRecommendations\.length"/)
  assert.match(source, /class="active-prediction-table"/)
  assert.match(source, /class="active-prediction-subheading active-prediction-suggestion-heading">预测<\/span>/)
  assert.match(source, /v-for="prediction in activePredictionRecommendations"/)
  assert.match(source, /class="active-prediction-line active-prediction-suggestion"/)
  assert.doesNotMatch(source, /active-prediction-tag/)
  assert.match(source, /class="active-prediction-subheading">其他可能<\/span>/)
  assert.match(source, /v-for="prediction in activePredictionAlternatives"/)
  assert.match(source, /class="active-prediction-line active-prediction-alternative"/)
  assert.match(source, /class="active-prediction-label"/)
  assert.match(source, /class="active-prediction-probability"/)
  assert.doesNotMatch(source, /active-prediction-rank/)
  assert.doesNotMatch(source, /`rank-\$\{prediction\.rank\}`/)
  assert.match(source, /formatPercent\(prediction\.probability, 1\)/)
  assert.doesNotMatch(source, />建议<\/span>/)
  assert.doesNotMatch(source, />备选<\/span>/)
  assert.match(source, /class="active-prediction-empty">等待预测<\/span>/)
  assert.doesNotMatch(source, /调谐中/)
  assert.match(source, /aria-label="撤回上一次录入的副词条"/)
  assert.match(source, /class="active-action-dock"/)
  assert.match(source, /class="active-action-button active-action-icon-button undo-action"/)
  assert.match(source, /class="ui-line-icon active-action-icon"[\s\S]+iconMask\(undoActionIcon\)/)
  assert.doesNotMatch(source, /<span>撤销<\/span>/)
  assert.doesNotMatch(source, /active-action-status/)
  assert.doesNotMatch(source, /<span>撤销上条<\/span>/)
  assert.match(source, /aria-label="弃置当前声骸"/)
  assert.match(source, /class="active-action-button active-action-icon-button discard-action"/)
  assert.match(source, /class="ui-line-icon active-action-icon"[\s\S]+iconMask\(trashIcon\)/)
  assert.doesNotMatch(source, /<span>弃置<\/span>/)
  assert.match(source, /aria-label="进入下一个声骸"/)
  assert.match(source, /class="active-action-button next-action"/)
  assert.match(source, /<span>下一个<\/span>/)
  assert.doesNotMatch(source, /iconMask\(arrowRightIcon\)/)
  assert.match(source, /class="active-record-main"/)
  assert.match(source, /class="[^"]*active-action-rail/)
  assert.match(style, /\.active-record-panel \{[\s\S]+grid-template-columns: minmax\(0, 1fr\) clamp\(232px, 30%, 248px\);/)
  assert.match(style, /\.active-record-main \{[\s\S]+display: grid;[\s\S]+grid-template-rows: auto minmax\(0, 1fr\);/)
  assert.match(style, /\.active-action-button \{[\s\S]+font-size: var\(--text-control\);[\s\S]+font-weight: var\(--weight-control\);/)
  assert.match(style, /\.active-record-panel \{[\s\S]+display: grid;/)
  assert.match(style, /\.active-record-panel \{[\s\S]+overflow: hidden;/)
  assert.match(style, /\.active-actions \{[\s\S]+grid-template-columns: 1fr;[\s\S]+align-self: stretch;/)
  assert.match(style, /\.active-action-rail \{[\s\S]+display: grid;[\s\S]+grid-template-rows: minmax\(0, 1fr\) auto;[\s\S]+align-content: stretch;[\s\S]+border-left: 1px solid rgba\(216, 226, 234, 0\.72\);[\s\S]+padding: 16px;[\s\S]+background: #f7f9fb;/)
  assert.match(style, /\.active-prediction-card \{[\s\S]+align-content: center;[\s\S]+padding-bottom: 16px;/)
  assert.match(style, /\.active-action-dock \{[\s\S]+grid-template-columns: 44px 44px minmax\(0, 1fr\);[\s\S]+gap: 8px;[\s\S]+border-top: 1px solid rgba\(216, 226, 234, 0\.72\);[\s\S]+padding-top: 12px;/)
  assert.match(style, /\.active-action-icon-button \{[\s\S]+width: 44px;[\s\S]+padding: 0;/)
  assert.doesNotMatch(style, /\.active-action-status \{/)
  assert.doesNotMatch(style, /\.active-action-anchor \{/)
  assert.match(style, /\.active-prediction-card \{[\s\S]+display: grid;[\s\S]+align-content: center;[\s\S]+min-height: 144px;[\s\S]+border: 0;[\s\S]+padding-bottom: 16px;[\s\S]+background: transparent;/)
  assert.doesNotMatch(style, /\.active-prediction-heading/)
  assert.match(style, /\.active-prediction-table \{[\s\S]+gap: 5px;/)
  assert.match(style, /\.active-prediction-line \{[\s\S]+grid-template-columns: minmax\(max-content, 1fr\) max-content;[\s\S]+gap: 6px;[\s\S]+border: 1px solid transparent;[\s\S]+border-radius: 10px;[\s\S]+padding: 5px 6px;/)
  assert.match(style, /\.active-prediction-suggestion \{[\s\S]+border-color: rgba\(44, 159, 112, 0\.12\);[\s\S]+background: rgba\(44, 159, 112, 0\.1\);/)
  assert.doesNotMatch(style, /\.active-prediction-suggestion \{[^}]+margin: 0 -/)
  assert.doesNotMatch(style, /\.active-prediction-suggestion \{[^}]+grid-template-columns: auto/)
  assert.doesNotMatch(style, /\.active-prediction-tag/)
  assert.match(style, /\.active-prediction-subheading \{[\s\S]+font-size: var\(--text-caption\);/)
  assert.match(style, /\.active-prediction-suggestion-heading \{[\s\S]+color: #2c7a59;/)
  assert.match(style, /\.active-prediction-alternative \{[\s\S]+border-color: transparent;[\s\S]+background: transparent;/)
  assert.match(style, /\.active-prediction-label \{[\s\S]+min-width: max-content;[\s\S]+overflow-wrap: normal;[\s\S]+white-space: nowrap;[\s\S]+word-break: keep-all;/)
  assert.match(style, /\.active-prediction-probability \{[\s\S]+min-width: max-content;/)
  assert.doesNotMatch(style, /\.active-prediction-label \{[^}]+white-space: normal;/)
  assert.doesNotMatch(style, /\.active-prediction-label \{[^}]+text-overflow: ellipsis;/)
  assert.doesNotMatch(style, /\.active-prediction-label \{[^}]+overflow: hidden;/)
  assert.match(style, /\.active-prediction-probability \{[\s\S]+font-variant-numeric: tabular-nums;/)
  assert.doesNotMatch(style, /\.active-prediction-rank/)
  assert.doesNotMatch(style, /\.active-prediction-line\.rank-/)
  assert.match(style, /\.active-action-button \{[\s\S]+width: 100%;[\s\S]+min-height: 44px;[\s\S]+border-radius: 12px;/)
  assert.match(style, /\.active-action-icon \{[\s\S]+width: 18px;[\s\S]+height: 18px;/)
  assert.doesNotMatch(style, /\.icon-only-action \{/)
  assert.doesNotMatch(style, /\.discard-action \{[^}]+min-height:/)
  assert.match(style, /\.roll-strip \{[\s\S]+grid-template-rows: repeat\(5, minmax\(0, 1fr\)\);/)
  assert.match(style, /\.roll-strip span \{[^}]+grid-template-columns: 24px minmax\(0, 1fr\) 76px;[^}]+min-height: 0;/)
  assert.doesNotMatch(style, /\.roll-slot \{[^}]+min-height:/)
  assert.doesNotMatch(style, /\.roll-strip span,\s*\n\s*\.roll-slot \{[^}]+min-height:/)
  assert.match(style, /\.roll-value \{[\s\S]+justify-self: end;[\s\S]+min-width: 76px;[\s\S]+text-align: right;/)
  assert.match(style, /\.record-actions \{[\s\S]+align-self: stretch;[\s\S]+margin-top: 0;/)
  assert.match(style, /@media \(max-width: 860px\) \{[\s\S]+\.active-action-rail \{[\s\S]+grid-template-columns: 1fr;[\s\S]+grid-template-rows: minmax\(128px, auto\) auto;/)
  assert.match(style, /@media \(max-width: 860px\) \{[\s\S]+\.roll-strip span \{[^}]+min-height: 36px;/)
  assert.doesNotMatch(style, /\.active-secondary-actions/)
  assert.doesNotMatch(style, /\.active-action-button \.active-action-icon/)
})

test('dark active echo actions use a single tonal hierarchy', async () => {
  const style = await readFile(new URL('../../styles/features/workspace.css', import.meta.url), 'utf8')

  assert.match(style, /\.app-shell\.theme-dark \.undo-action \{[\s\S]+color: #c8d5df;[\s\S]+background: transparent;/)
  assert.match(style, /\.app-shell\.theme-dark \.undo-action:hover:not\(:disabled\) \{[\s\S]+border-color: rgba\(93, 168, 255, 0\.2\);[\s\S]+color: #e8f3ff;[\s\S]+background: rgba\(93, 168, 255, 0\.1\);/)
  assert.match(style, /\.app-shell\.theme-dark \.discard-action \{[\s\S]+color: #c8d5df;[\s\S]+background: transparent;/)
  assert.match(style, /\.app-shell\.theme-dark \.discard-action:hover:not\(:disabled\) \{[\s\S]+border-color: rgba\(255, 105, 128, 0\.24\);[\s\S]+color: #ffd4db;[\s\S]+background: rgba\(255, 105, 128, 0\.12\);/)
  assert.match(style, /\.app-shell\.theme-dark \.next-action \{[\s\S]+border-color: #2361b7;[\s\S]+color: #ffffff;[\s\S]+background: #2361b7;/)
  assert.match(style, /\.app-shell\.theme-dark \.next-action:hover:not\(:disabled\) \{[\s\S]+border-color: #2a73d1;[\s\S]+background: #2a73d1;/)
})

test('echo workbench keeps tier values calm and probabilities secondary', async () => {
  const source = await readFile(new URL('./EchoWorkbenchView.vue', import.meta.url), 'utf8')
  const style = await readFile(new URL('../../styles/features/workspace.css', import.meta.url), 'utf8')

  assert.match(source, /formatSubstatTierNumber/)
  assert.match(source, /formatSubstatTierUnit/)
  assert.match(source, /class="tier-value"/)
  assert.match(source, /class="tier-unit"/)
  assert.match(source, /class="tier-probability"/)
  assert.match(source, /formatPercent\(tier\.probability, 1\)/)
  assert.match(style, /\.tier-grid button \{[\s\S]+padding: 5px 10px;/)
  assert.match(style, /\.tier-value \{[\s\S]+font-size: var\(--text-data-md\); font-weight: var\(--weight-data\);/)
  assert.match(style, /\.tier-unit \{[\s\S]+font-size: var\(--text-label\);/)
  assert.match(style, /\.tier-probability \{[\s\S]+font-size: var\(--text-caption\); font-weight: var\(--weight-supporting\);/)
  assert.match(style, /\.tier-probability \{[\s\S]+font-variant-numeric: tabular-nums;/)
})

test('workspace styles keep long substat titles and recorded rows stable', async () => {
  const source = await readFile(new URL('./EchoWorkbenchView.vue', import.meta.url), 'utf8')
  const style = [
    await readFile(new URL('../../styles/features/workspace.css', import.meta.url), 'utf8'),
    await readFile(new URL('../../styles/features/workspace-active.css', import.meta.url), 'utf8'),
  ].join('\n')
  const topPredictedIcon = await readFile(new URL('../../assets/icons/fast-arrow-up.svg', import.meta.url), 'utf8')

  assert.match(source, /class="substat-title-line"/)
  assert.match(source, /import topPredictedIcon from '\.\.\/\.\.\/assets\/icons\/fast-arrow-up\.svg'/)
  assert.match(source, /class="top-predicted-indicator"/)
  assert.match(source, /aria-label="预测概率提升"/)
  assert.match(source, /class="ui-line-icon top-predicted-icon"/)
  assert.doesNotMatch(source, />预测最高<\/span>/)
  assert.match(style, /\.substat-title-line \{[\s\S]+grid-template-columns: minmax\(0, 1fr\) auto;/)
  assert.match(style, /\.top-predicted-indicator \{[\s\S]+width: 24px; height: 24px;/)
  assert.match(style, /\.top-predicted-icon \{[\s\S]+width: 14px; height: 14px;/)
  assert.match(topPredictedIcon, /M6 11L12 5L18 11/)
  assert.match(topPredictedIcon, /M6 19L12 13L18 19/)
  assert.doesNotMatch(topPredictedIcon, /a2 2 0 0 0/)
  assert.match(style, /\.substat-row \{[\s\S]+min-height: 70px;/)
  assert.doesNotMatch(style, /\.matrix-guide \{/)
  assert.match(style, /\.active-summary \{[\s\S]+grid-template-columns: minmax\(280px, 300px\) minmax\(0, 1fr\);/)
  assert.match(style, /\.active-summary \{[\s\S]+align-items: stretch;/)
  assert.match(style, /\.active-record-panel \{[\s\S]+grid-template-columns: minmax\(0, 1fr\) clamp\(232px, 30%, 248px\);/)
  assert.match(style, /\.active-record-main \{[\s\S]+grid-template-rows: auto minmax\(0, 1fr\);/)
  assert.match(style, /\.record-actions \{[\s\S]+align-self: stretch;[\s\S]+margin-top: 0;/)
  assert.doesNotMatch(style, /\.active-action-status \{/)
  assert.match(style, /\.app-shell\.theme-dark \.active-action-rail \{[\s\S]+background: #14212b;/)
  assert.match(style, /\.app-shell\.theme-dark \.active-prediction-card \{[\s\S]+border-color: transparent;[\s\S]+background: transparent;/)
  assert.match(style, /\.app-shell\.theme-dark \.active-prediction-suggestion \{[\s\S]+background: rgba\(55, 179, 127, 0\.14\);/)
  assert.match(style, /\.app-shell\.theme-dark \.active-prediction-suggestion-heading \{[\s\S]+color: #9ed9b8;/)
  assert.doesNotMatch(style, /\.app-shell\.theme-dark \.active-prediction-tag/)
  assert.match(style, /\.app-shell\.theme-dark \.active-prediction-alternative \{[\s\S]+color: #b5c8bb;/)
  assert.doesNotMatch(style, /\.app-shell\.theme-dark \.active-prediction-line\.rank-/)
  assert.doesNotMatch(style, /\.active-control-panel \{/)
  assert.match(style, /\.roll-strip span \{[\s\S]+grid-template-columns: 24px minmax\(0, 1fr\) 76px;/)
  assert.doesNotMatch(style, /\.roll-slot \{[^}]+min-height:/)
  assert.match(style, /\.roll-slot\.pending \{[\s\S]+color: var\(--stone\);/)
  assert.match(style, /\.substat-meta \{[\s\S]+min-height: 46px;/)
  assert.match(style, /\.substat-row\.top-predicted-row \{\s+border-color: rgba\(44, 159, 112, 0\.52\);\s+background: rgba\(44, 159, 112, 0\.08\);\s+\}/)
  assert.match(style, /\.substat-row\.recorded \{[\s\S]+box-shadow: none;/)
})

test('echo setup keeps main stat changes compact and softly animated', async () => {
  const source = await readFile(new URL('./EchoWorkbenchView.vue', import.meta.url), 'utf8')
  const layoutSource = await readFile(new URL('./useEchoWorkbenchLayout.js', import.meta.url), 'utf8')
  const style = await readFile(new URL('../../styles/features/workspace.css', import.meta.url), 'utf8')

  assert.match(source, /import \{ filterSonataEffects, useEchoWorkbenchLayout \} from '\.\/useEchoWorkbenchLayout'/)
  assert.match(layoutSource, /const mainStatRowRef = ref\(null\)/)
  assert.match(layoutSource, /const mainStatRowStyle = computed/)
  assert.match(layoutSource, /function clearMainStatRowHeight/)
  assert.match(layoutSource, /async function animateMainStatRowChange/)
  assert.match(layoutSource, /legalMainStats\.value\.join\('\|'\)/)
  assert.match(layoutSource, /function measureMainStatRowContentHeight/)
  assert.match(layoutSource, /mainStatRowRef\.value\.firstElementChild/)
  assert.doesNotMatch(layoutSource, /row\.scrollHeight/)
  assert.match(source, /<div\s+ref="mainStatRowRef"\s+class="main-stat-row-shell"\s+:style="mainStatRowStyle"\s+@transitionend="clearMainStatRowHeight"\s*>/)
  assert.match(source, /<TransitionGroup name="main-stat-option" tag="div" class="option-row main-stat-row">/)
  assert.match(style, /\.main-stat-row-shell \{[\s\S]+transition: height 160ms ease-out;/)
  assert.match(style, /\.main-stat-row \{[\s\S]+align-content: start;/)
  assert.doesNotMatch(style, /\.main-stat-row \{[\s\S]+min-height: 148px;/)
  assert.match(style, /\.main-stat-option-move,\s+\.main-stat-option-enter-active,\s+\.main-stat-option-leave-active \{[\s\S]+transition: opacity 140ms ease-out, transform 140ms ease-out;/)
  assert.match(style, /\.main-stat-option-enter-from,\s+\.main-stat-option-leave-to \{[\s\S]+opacity: 0;/)
})

test('echo workbench emits commands without owning persistence', async () => {
  const source = await readFile(new URL('./EchoWorkbenchView.vue', import.meta.url), 'utf8')

  assert.match(source, /defineEmits\(\['config-change', 'undo', 'discard', 'next', 'select-tier', 'preview-change'\]\)/)
  assert.match(source, /emit\('config-change', \{ sonata: effect\.name \}\)/)
  assert.match(source, /emit\('select-tier', \{ row, tier \}\)/)
  assert.doesNotMatch(source, /from '\.\.\/\.\.\/services\/api'/)
})

test('tier saving disables the full matrix and recorded rows emphasize only the chosen tier', async () => {
  const source = await readFile(new URL('./EchoWorkbenchView.vue', import.meta.url), 'utf8')
  const style = await readFile(new URL('../../styles/features/workspace.css', import.meta.url), 'utf8')
  const recordedRule = style.match(/\.substat-row\.recorded \{[^}]+\}/)?.[0] || ''

  assert.match(source, /function rowPendingTierKey\(row\)/)
  assert.match(source, /props\.pendingTierKey\.startsWith\(`\$\{row\.substat_type\}:`\)/)
  assert.match(source, /:disabled="Boolean\(row\.recorded\) \|\| Boolean\(pendingTierKey\)"/)
  assert.match(source, /'recorded-tier': isRecordedTier\(row, tier\)/)
  assert.match(source, /'saving-tier': isTierPending\(row, tier\)/)
  assert.match(source, /:aria-busy="isTierPending\(row, tier\)"/)
  assert.match(source, />保存中</)
  assert.match(source, /Boolean\(props\.pendingTierKey\)/)
  assert.match(style, /\.tier-grid button\.recorded-tier:disabled/)
  assert.match(style, /\.tier-grid button\.saving-tier:disabled/)
  assert.doesNotMatch(recordedRule, /box-shadow: inset 4px/)
})

test('echo workbench disables costs unavailable for the selected sonata', async () => {
  const source = await readFile(new URL('./EchoWorkbenchView.vue', import.meta.url), 'utf8')
  const style = await readFile(new URL('../../styles/features/workspace.css', import.meta.url), 'utf8')

  assert.match(source, /const costOptions = Object\.freeze\(\[1, 3, 4\]\)/)
  assert.match(source, /const selectedSonataEffect = computed/)
  assert.match(source, /const availableCosts = computed/)
  assert.match(source, /function isCostAvailable\(cost\)/)
  assert.match(source, /function selectCost\(cost\)/)
  assert.match(source, /v-for="cost in costOptions"/)
  assert.match(source, /:disabled="!isCostAvailable\(cost\)"/)
  assert.match(source, /@click="selectCost\(cost\)"/)
  assert.match(style, /\.option-row button:disabled \{[\s\S]+opacity: 0\.46;/)
  assert.match(style, /\.app-shell\.theme-dark \.option-row button:disabled \{[\s\S]+background: var\(--surface-soft\);/)
})

test('echo workbench uses equal outer columns with viewport-sticky setup content', async () => {
  const source = await readFile(new URL('./EchoWorkbenchView.vue', import.meta.url), 'utf8')
  const layout = await readFile(new URL('./useEchoWorkbenchLayout.js', import.meta.url), 'utf8')
  const style = await readFile(new URL('../../styles/features/workspace.css', import.meta.url), 'utf8')

  assert.match(source, /class="setup-panel-content"/)
  assert.doesNotMatch(source, /setupPanelStyle|:style="setupPanelStyle"/)
  assert.doesNotMatch(layout, /setupPanelHeight|syncSetupPanelHeight|galleryPanelRef/)
  assert.match(layout, /const sonataGridRef = ref\(null\)/)
  assert.match(layout, /async function focusActiveSonata/)
  assert.match(layout, /querySelector\('button\.active'\)/)
  assert.match(layout, /visibleSonataNames\.value\.join\('\|'\)/)
  assert.match(style, /\.workspace-grid \{[\s\S]+align-items: stretch;/)
  assert.match(style, /\.workspace-sidebar \{[\s\S]+align-self: stretch;/)
  assert.match(style, /\.setup-panel-content \{[\s\S]+position: sticky;[\s\S]+height: calc\(100dvh - 104px\);[\s\S]+max-height: calc\(100dvh - 104px\);/)
  assert.match(style, /\.create-panel \.sonata-grid \{[\s\S]+height: 0;[\s\S]+overflow-y: auto;/)
})

test('workbench stays dense and keeps eight tiers on one row at medium desktop widths', async () => {
  const workspaceStyle = await readFile(new URL('../../styles/features/workspace.css', import.meta.url), 'utf8')
  const activeStyle = await readFile(new URL('../../styles/features/workspace-active.css', import.meta.url), 'utf8')

  assert.match(workspaceStyle, /@media \(min-width: 1180px\) and \(max-width: 1440px\) \{/)
  assert.match(workspaceStyle, /@media \(min-width: 1180px\) and \(max-width: 1440px\) \{[\s\S]+\.workspace-grid \{[^}]+grid-template-columns: minmax\(300px, 320px\) minmax\(0, 1fr\);/)
  assert.match(workspaceStyle, /@media \(min-width: 1180px\) and \(max-width: 1440px\) \{[\s\S]+\.main-stat-row button \{[^}]+flex-basis: 112px;/)
  assert.match(workspaceStyle, /@media \(min-width: 1180px\) and \(max-width: 1440px\) \{[\s\S]+\.tier-grid \{[^}]+grid-template-columns: repeat\(8, minmax\(0, 1fr\)\);/)
  assert.match(workspaceStyle, /@media \(min-width: 1180px\) and \(max-width: 1440px\) \{[\s\S]+\.tier-grid button \{[^}]+min-width: 0;/)
  assert.match(activeStyle, /@media \(min-width: 1180px\) and \(max-width: 1440px\) \{/)
  assert.match(activeStyle, /@media \(min-width: 1180px\) and \(max-width: 1440px\) \{[\s\S]+\.active-summary \{[^}]+grid-template-columns: minmax\(248px, 264px\) minmax\(0, 1fr\);/)
  assert.match(activeStyle, /@media \(min-width: 1180px\) and \(max-width: 1440px\) \{[\s\S]+\.active-echo-name-title \{[^}]+text-overflow: ellipsis;[^}]+white-space: nowrap;/)
})
