import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

test('context detail progress uses the local clamp helper', async () => {
  const source = await readFile(new URL('./App.vue', import.meta.url), 'utf8')

  assert.match(source, /function contextCheckProgress\(check\) \{\s+return clampNumber\(/)
  assert.doesNotMatch(source, /function contextCheckProgress\(check\) \{\s+return clamp\(/)
})

test('context and rule details show evidence directly with a single evidence tab', async () => {
  const source = await readFile(new URL('./App.vue', import.meta.url), 'utf8')

  assert.match(source, /function modelInsightView\(model\) \{\s+if \(model\.key === 'context' \|\| model\.key === 'rule'\) \{\s+return 'evidence'/)
  assert.match(source, /function modelInsightTabs\(model\) \{\s+if \(model\.key === 'context' \|\| model\.key === 'rule'\) \{\s+return model\.tabs\.filter\(\(tab\) => tab\.key === 'evidence'\)/)
  assert.match(source, /function modelShowsInsightTabs\(model\) \{\s+return modelInsightTabs\(model\)\.length > 0/)
  assert.match(source, /v-if="modelShowsInsightTabs\(model\)" class="model-insight-tabs"/)
  assert.match(source, /v-for="tab in modelInsightTabs\(model\)"/)
})

test('evaluation summary model names highlight linked fusion cards', async () => {
  const source = await readFile(new URL('./App.vue', import.meta.url), 'utf8')

  assert.match(source, /const highlightedSummaryModelKey = ref\(null\)/)
  assert.match(source, /class="summary-model-link summary-model-link-dominant"/)
  assert.match(source, /'summary-linked': highlightedSummaryModelKey === row\.key/)
  assert.match(source, /@mouseenter="setSummaryModelHighlight\(/)
})

test('topbar exposes an accessible theme toggle that resets to system color scheme on load', async () => {
  const appSource = await readFile(new URL('./App.vue', import.meta.url), 'utf8')
  const styleSource = await readFile(new URL('./style.css', import.meta.url), 'utf8')

  assert.match(appSource, /const themeMode = ref\(readInitialTheme\(\)\)/)
  assert.match(appSource, /const isDarkTheme = computed\(\(\) => themeMode\.value === 'dark'\)/)
  assert.match(appSource, /import moonIcon from '\.\/assets\/icons\/moon\.svg'/)
  assert.match(appSource, /import sunIcon from '\.\/assets\/icons\/sun\.svg'/)
  assert.match(appSource, /function iconMask\(source\)/)
  assert.match(appSource, /window\.matchMedia\?\.\('\(prefers-color-scheme: dark\)'\)\.matches/)
  assert.doesNotMatch(appSource, /localStorage\.getItem\('wuwa-theme'\)/)
  assert.doesNotMatch(appSource, /localStorage\.setItem\('wuwa-theme'/)
  assert.match(appSource, /<main class="app-shell" :class="\{ 'theme-dark': isDarkTheme \}">/)
  assert.match(appSource, /class="theme-toggle-button"/)
  assert.match(appSource, /:aria-pressed="isDarkTheme"/)
  assert.match(appSource, /:aria-label="themeToggleLabel"/)
  assert.match(appSource, /class="ui-line-icon theme-toggle-icon"/)
  assert.match(appSource, /iconMask\(isDarkTheme \? sunIcon : moonIcon\)/)
  assert.match(styleSource, /\.ui-line-icon \{/)
  assert.match(styleSource, /\.app-shell\.theme-dark \{/)
  assert.match(styleSource, /\.theme-toggle-button \{/)
  assert.match(styleSource, /\.theme-dark \.theme-toggle-icon \{/)
  assert.match(styleSource, /\.app-shell\.theme-dark \.history-filter-chip \{/)
  assert.match(styleSource, /\.app-shell\.theme-dark \.echo-roll-list span \{/)
  assert.match(styleSource, /\.app-shell\.theme-dark \.active-config-chips span \{/)
  assert.match(styleSource, /\.app-shell\.theme-dark \.active-summary \{/)
  assert.match(styleSource, /\.app-shell\.theme-dark \.tier-grid button \{/)
  assert.match(styleSource, /\.app-shell\.theme-dark \.topbar \.pill-tabs \{/)
  assert.match(styleSource, /\.app-shell\.theme-dark \.auth-shell-home \.showcase-card,/) 
  assert.match(styleSource, /\.app-shell\.theme-dark \.login-info-grid div \{/)
  assert.match(styleSource, /\.app-shell\.theme-dark \.button-buy \{/)
  assert.match(styleSource, /\.app-shell\.theme-dark \.error-text \{/)
  assert.match(styleSource, /\.app-shell\.theme-dark \.stats-summary-bar article,/) 
  assert.match(styleSource, /\.app-shell\.theme-dark \.evaluation-status-chip,/) 
  assert.match(styleSource, /\.app-shell\.theme-dark \.model-bars article,/) 
  assert.match(styleSource, /\.app-shell\.theme-dark \.evaluation-summary-kicker \{/)
  assert.match(styleSource, /\.app-shell\.theme-dark \.model-bars-head \{/)
  assert.match(styleSource, /\.app-shell\.theme-dark \.model-row-detail \.model-insight-card \{/)
  assert.match(styleSource, /\.app-shell\.theme-dark \.model-chart-bayes \{/)
  assert.match(styleSource, /\.app-shell\.theme-dark \.bayes-path-list article \{/)
  assert.match(styleSource, /\.app-shell\.theme-dark \.cycle-window-grid article,/) 
  assert.match(styleSource, /\.app-shell\.theme-dark \.markov-axis-chart \{/)
  assert.match(styleSource, /\.app-shell\.theme-dark \.rule-deviation-chart \{/)
  assert.match(styleSource, /\.app-shell\.theme-dark \.context-check-grid \{/)
  assert.match(styleSource, /\.app-shell\.theme-dark \.model-metric-grid \{/)
  assert.match(styleSource, /\.app-shell\.theme-dark \.model-weight-change \{/)
})

test('topbar uid chip shows the bound game account uid without local quick switching', async () => {
  const appSource = await readFile(new URL('./App.vue', import.meta.url), 'utf8')
  const styleSource = await readFile(new URL('./style.css', import.meta.url), 'utf8')

  assert.match(appSource, /import \{ normalizePlayerUid \} from '\.\/services\/playerUid'/)
  assert.match(appSource, /const boundPlayerUid = computed\(\(\) => gameAccount\.defaultAccount\.value\?\.uid \|\| ''\)/)
  assert.match(appSource, /class="uid-chip"/)
  assert.match(appSource, /class="uid-status-dot"/)
  assert.match(appSource, /class="uid-chip-label">UID<\/span>/)
  assert.match(appSource, /class="uid-chip-value">\{\{ boundPlayerUid \|\|/)
  assert.doesNotMatch(appSource, /aria-haspopup="dialog"/)
  assert.doesNotMatch(appSource, /class="uid-switcher-menu"/)
  assert.doesNotMatch(appSource, /uidQuickSwitchRows/)
  assert.doesNotMatch(appSource, /switchPlayerUid/)
  assert.doesNotMatch(appSource, /readRecentPlayerUids/)
  assert.doesNotMatch(appSource, /addRecentPlayerUid/)
  assert.match(styleSource, /\.uid-status-dot \{/)
  assert.match(styleSource, /\.uid-chip-label \{/)
  assert.match(styleSource, /\.uid-chip-value \{/)
})

test('floating history controls use the shared line icon system', async () => {
  const appSource = await readFile(new URL('./App.vue', import.meta.url), 'utf8')
  const readmeSource = await readFile(new URL('./assets/icons/README.md', import.meta.url), 'utf8')

  assert.match(appSource, /import historyPinnedIcon from '\.\/assets\/icons\/pin\.svg'/)
  assert.match(appSource, /import historyShowcaseIcon from '\.\/assets\/icons\/layout-list-lucide\.svg'/)
  assert.match(appSource, /import historyMinimizeIcon from '\.\/assets\/icons\/panel-left\.svg'/)
  assert.match(appSource, /class="ui-line-icon history-action-icon"/)
  assert.match(appSource, /iconMask\(historyPinnedIcon\)/)
  assert.match(appSource, /iconMask\(historyShowcaseIcon\)/)
  assert.match(appSource, /iconMask\(historyMinimizeIcon\)/)
  assert.match(readmeSource, /Lucide Icons/)
})

test('milestone 3 uses account login and locks workbench until default game uid is bound', async () => {
  const appSource = await readFile(new URL('./App.vue', import.meta.url), 'utf8')
  const styleSource = await readFile(new URL('./style.css', import.meta.url), 'utf8')

  assert.match(appSource, /import \{ useAuth \} from '\.\/composables\/useAuth'/)
  assert.match(appSource, /import \{ useGameAccount \} from '\.\/composables\/useGameAccount'/)
  assert.match(appSource, /const authForm = ref\(\{\s+username: localStorage\.getItem\('wuwa-login-username'\) \|\| '',\s+password: '',\s+mode: 'login'/)
  assert.match(appSource, /await auth\.signIn\(payload\)/)
  assert.match(appSource, /await gameAccount\.loadGameAccounts\(\)/)
  assert.match(appSource, /const selectedGameAccountId = computed\(\(\) => gameAccount\.defaultAccount\.value\?\.id \|\| null\)/)
  assert.match(appSource, /const boundPlayerUid = computed\(\(\) => gameAccount\.defaultAccount\.value\?\.uid \|\| ''\)/)
  assert.match(appSource, /v-else-if="gameAccount\.workspaceLocked\.value" class="uid-setup-shell"/)
  assert.match(appSource, /<section class="locked-workbench product-panel">/)
  assert.match(appSource, /@submit\.prevent="submitUidBinding"/)
  assert.match(appSource, /await gameAccount\.bindDefaultUid\(uidBinding\.value\)/)
  assert.match(appSource, /await refreshAll\(\)/)
  assert.doesNotMatch(appSource, /uidCredentials/)
  assert.doesNotMatch(appSource, /submitUidLogin/)
  assert.doesNotMatch(appSource, /switchPlayerUid/)
  assert.doesNotMatch(appSource, /readRecentPlayerUids/)
  assert.doesNotMatch(appSource, /wuwa-player-uid/)
  assert.match(styleSource, /\.locked-workbench \{/)
  assert.match(styleSource, /\.uid-binding-form \{/)
  assert.match(styleSource, /\.uid-setup-shell \.locked-workbench \{[\s\S]+width: min\(560px, 100%\);/)
  assert.match(styleSource, /\.uid-binding-form \{[\s\S]+grid-template-columns: minmax\(0, 1fr\) 112px;/)
})

test('locked uid binding state shows a focused setup page without workbench chrome', async () => {
  const appSource = await readFile(new URL('./App.vue', import.meta.url), 'utf8')
  const styleSource = await readFile(new URL('./style.css', import.meta.url), 'utf8')

  assert.match(appSource, /<section v-else-if="gameAccount\.workspaceLocked\.value" class="uid-setup-shell">/)
  assert.match(appSource, /<header class="uid-setup-topbar">/)
  assert.match(appSource, /class="pill-tabs disabled-tabs"/)
  assert.match(appSource, /disabled>工作台<\/button>/)
  assert.match(appSource, /disabled>统计<\/button>/)
  assert.match(appSource, /disabled>评估<\/button>/)
  assert.match(appSource, /<div class="uid-setup-content">/)
  assert.match(appSource, /<section class="locked-workbench product-panel">/)
  assert.doesNotMatch(appSource, /class="uid-setup-step"/)
  assert.match(appSource, /<h2>绑定鸣潮 UID<\/h2>/)
  assert.match(appSource, /用于保存声骸记录和统计数据。/)
  assert.match(appSource, /<label>\s+UID\s+<input/)
  assert.match(appSource, /placeholder="输入你的 UID"/)
  assert.match(appSource, /\{\{ saving \? '保存中' : '保存' \}\}/)
  assert.match(appSource, /<section v-else class="dashboard">/)
  assert.doesNotMatch(appSource, /<section v-if="gameAccount\.workspaceLocked\.value" class="locked-workbench product-panel">/)
  assert.match(styleSource, /\.uid-setup-topbar \{[\s\S]+width: 100%;/)
  assert.match(styleSource, /\.uid-setup-topbar \{[\s\S]+margin: 0 auto;/)
  assert.match(styleSource, /\.uid-setup-shell \{[\s\S]+width: min\(1360px, calc\(100% - 64px\)\);/)
  assert.match(styleSource, /\.uid-setup-content \{[\s\S]+padding-top: clamp\(48px, 8vh, 88px\);/)
  assert.match(styleSource, /\.locked-workbench \{[\s\S]+max-width: 560px;/)
  assert.match(styleSource, /\.locked-workbench \{[\s\S]+padding: 28px 32px;/)
  assert.match(styleSource, /\.uid-setup-content > \.error-text \{[\s\S]+width: min\(560px, 100%\);/)
  assert.match(styleSource, /\.disabled-tabs button \{/)
  assert.match(styleSource, /\.disabled-tabs button\.active \{[\s\S]+background: rgba\(23, 105, 210, 0\.08\);/)
  assert.match(styleSource, /input:focus \{[\s\S]+box-shadow: 0 0 0 2px rgba\(24, 118, 242, 0\.1\);/)
})

test('milestone 3 scopes frontend data calls to the selected game account', async () => {
  const appSource = await readFile(new URL('./App.vue', import.meta.url), 'utf8')

  assert.match(appSource, /await listEchoes\(selectedGameAccountId\.value\)/)
  assert.match(appSource, /await createEcho\(\{\s+display_name: '',[\s\S]+?\}, selectedGameAccountId\.value\)/)
  assert.match(appSource, /stats\.value = await getStats\(selectedGameAccountId\.value\)/)
  assert.match(appSource, /evaluation\.value = await getModelEvaluation\(selectedGameAccountId\.value\)/)
})

test('milestone 6 shows recognition summary, review list, and revert action', async () => {
  const appSource = await readFile(new URL('./App.vue', import.meta.url), 'utf8')
  const styleSource = await readFile(new URL('./style.css', import.meta.url), 'utf8')

  assert.match(appSource, /listRecognitionSessions/)
  assert.match(appSource, /listRecognitionSnapshots/)
  assert.match(appSource, /revertRecognitionSnapshot/)
  assert.match(appSource, /import refreshIcon from '\.\/assets\/icons\/refresh-cw\.svg'/)
  assert.match(appSource, /import checkIcon from '\.\/assets\/icons\/check\.svg'/)
  assert.match(appSource, /import xIcon from '\.\/assets\/icons\/x\.svg'/)
  assert.match(appSource, /const recognitionRefreshing = ref\(false\)/)
  assert.match(appSource, /const recognitionRefreshStatus = ref\(''\)/)
  assert.match(appSource, /let recognitionRefreshFeedbackTimer = null/)
  assert.match(appSource, /const recognitionRefreshIcon = computed\(\(\) => \{/)
  assert.match(appSource, /recognitionRefreshStatus\.value === 'success'[\s\S]+return checkIcon/)
  assert.match(appSource, /recognitionRefreshStatus\.value === 'error'[\s\S]+return xIcon/)
  assert.match(appSource, /const recognitionRefreshDisabled = computed\(\(\) => saving\.value \|\| recognitionRefreshing\.value \|\| Boolean\(recognitionRefreshStatus\.value\)\)/)
  assert.match(appSource, /const recognitionSessions = ref\(\[\]\)/)
  assert.match(appSource, /const recognitionSnapshots = ref\(\[\]\)/)
  assert.match(appSource, /const latestRecognitionSession = computed/)
  assert.match(appSource, /const recognitionReviewRows = computed/)
  assert.match(appSource, /async function refreshRecognition\(\{ silent = false \} = \{\}\)/)
  assert.match(appSource, /await refreshRecognition\(\{ silent: true \}\)/)
  assert.match(appSource, /function setRecognitionRefreshStatus\(status\)/)
  assert.match(appSource, /setRecognitionRefreshStatus\('success'\)/)
  assert.match(appSource, /setRecognitionRefreshStatus\('error'\)/)
  assert.match(appSource, /async function revertSnapshot\(snapshot\)/)
  assert.match(appSource, /class="recognition-panel/)
  assert.match(appSource, /aria-label="刷新识别结果"/)
  assert.match(appSource, /:class="\[recognitionRefreshStatus, \{ refreshing: recognitionRefreshing \}\]"/)
  assert.match(appSource, /:disabled="recognitionRefreshDisabled"/)
  assert.match(appSource, /:aria-busy="recognitionRefreshing"/)
  assert.match(appSource, /iconMask\(recognitionRefreshIcon\)/)
  assert.match(appSource, /本地自动识别/)
  assert.match(appSource, /recognitionSecondarySummary/)
  assert.match(appSource, /class="recognition-summary-strip"/)
  assert.match(appSource, /class="recognition-metric-grid"/)
  assert.match(appSource, /snapshot_count/)
  assert.match(appSource, /saved_roll_count/)
  assert.match(appSource, /created_echo_count/)
  assert.match(appSource, /updated_echo_count/)
  assert.match(appSource, /conflict_count/)
  assert.match(appSource, /reverted_count/)
  assert.match(appSource, /v-for="snapshot in recognitionReviewRows"/)
  assert.match(appSource, /@click="revertSnapshot\(snapshot\)"/)
  assert.match(styleSource, /\.recognition-panel \{/)
  assert.match(styleSource, /\.recognition-refresh-button \{/)
  assert.match(styleSource, /\.recognition-refresh-button:hover:not\(:disabled\) \.ui-line-icon \{/)
  assert.match(styleSource, /\.recognition-refresh-button\.refreshing \.ui-line-icon \{/)
  assert.match(styleSource, /@keyframes recognition-refresh-spin/)
  assert.match(styleSource, /\.recognition-refresh-button\.success \{/)
  assert.match(styleSource, /\.recognition-refresh-button\.error \{/)
  assert.match(styleSource, /\.recognition-summary-strip \{/)
  assert.match(styleSource, /\.recognition-metric-grid \{/)
  assert.match(styleSource, /\.recognition-review-row \{/)
  assert.match(styleSource, /\.app-shell\.theme-dark \.recognition-summary-strip \{/)
  assert.match(styleSource, /\.app-shell\.theme-dark \.recognition-review-row,/)
})

test('tier clicks update the active echo without blocking on full workspace refresh', async () => {
  const appSource = await readFile(new URL('./App.vue', import.meta.url), 'utf8')
  const styleSource = await readFile(new URL('./style.css', import.meta.url), 'utf8')
  const clickTierBody = appSource.match(/async function clickTier\(row, tier\) \{[\s\S]+?\n\}/)?.[0] || ''
  const undoBody = appSource.match(/async function undoActiveSubstat\(\) \{[\s\S]+?\n\}/)?.[0] || ''

  assert.match(appSource, /function appendRollToEcho\(echoId, roll\)/)
  assert.match(appSource, /function refreshInsightsInBackground\(\)/)
  assert.match(appSource, /function refreshActiveInBackground\(\)/)
  assert.match(appSource, /const pendingTierKey = ref\(''\)/)
  assert.match(appSource, /let activePredictionRefreshToken = 0/)
  assert.match(appSource, /let insightsRefreshTimer = null/)
  assert.match(appSource, /clearTimeout\(insightsRefreshTimer\)/)
  assert.match(appSource, /setTimeout\(\(\) => \{/)
  assert.match(appSource, /function rowHasPendingTier\(row\)/)
  assert.match(clickTierBody, /const roll = await addSubstat/)
  assert.match(clickTierBody, /appendRollToEcho\(echo\.id, optimisticRoll\)/)
  assert.match(clickTierBody, /replaceOptimisticRollInEcho\(echo\.id, optimisticRoll\.id, roll\)/)
  assert.match(clickTierBody, /refreshActiveInBackground\(\)/)
  assert.match(clickTierBody, /refreshInsightsInBackground\(\)/)
  assert.doesNotMatch(clickTierBody, /saving\.value = true/)
  assert.doesNotMatch(clickTierBody, /await refreshActive\(\)/)
  assert.doesNotMatch(clickTierBody, /refreshAll\(\)/)
  assert.match(appSource, /:disabled="Boolean\(row\.recorded\) \|\| isTierPending\(row, tier\)"/)
  assert.match(appSource, /v-memo="\[row\.recorded\?\.id, row\.recorded\?\.tier_value, row\.candidate\?\.p_final, row\.candidate\?\.baseline_deviation, row\.topPredicted, rowHasPendingTier\(row\)\]"/)
  assert.doesNotMatch(appSource, /:disabled="Boolean\(row\.recorded\) \|\| saving"/)
  assert.doesNotMatch(appSource, /activeEchoId\.value\}:\$\{activeEcho\.value\?\.substats\.length/)
  assert.match(styleSource, /\.substat-row \{[\s\S]+contain: layout paint;/)
  assert.match(undoBody, /replaceEcho\(result\.echo\)/)
  assert.match(undoBody, /refreshInsightsInBackground\(\)/)
  assert.doesNotMatch(undoBody, /refreshAll\(\)/)
})

test('tier clicks optimistically update before waiting for the save request', async () => {
  const appSource = await readFile(new URL('./App.vue', import.meta.url), 'utf8')
  const clickTierBody = appSource.match(/async function clickTier\(row, tier\) \{[\s\S]+?\n\}/)?.[0] || ''

  assert.match(appSource, /function buildOptimisticRoll\(row, tier\)/)
  assert.match(appSource, /function removeOptimisticRollFromEcho\(echoId, optimisticRollId\)/)
  assert.match(appSource, /function replaceOptimisticRollInEcho\(echoId, optimisticRollId, roll\)/)
  assert.match(clickTierBody, /optimisticRoll = buildOptimisticRoll\(row, tier\)/)
  assert.match(clickTierBody, /appendRollToEcho\(echo\.id, optimisticRoll\)[\s\S]+const roll = await addSubstat/)
  assert.match(clickTierBody, /replaceOptimisticRollInEcho\(echo\.id, optimisticRoll\.id, roll\)/)
  assert.match(clickTierBody, /removeOptimisticRollFromEcho\(optimisticEchoId, optimisticRoll\.id\)/)
})

test('new echo creation lets backend allocate echo uid', async () => {
  const source = await readFile(new URL('./App.vue', import.meta.url), 'utf8')

  assert.doesNotMatch(source, /generateNumericEchoUid/)
  assert.doesNotMatch(source, /nextEchoSequence/)
  assert.doesNotMatch(source, /function generateEchoUid/)
  assert.doesNotMatch(source, /echo_uid:\s*generateEchoUid\(\)/)
})

test('evaluation summary keeps original copy while styling dominant and auxiliary models differently', async () => {
  const source = await readFile(new URL('./App.vue', import.meta.url), 'utf8')

  assert.match(source, /const activeRows = weightRows\.value/)
  assert.match(source, /const dominantKey = modelDetailSummary\.value\.dominantModel \|\| activeRows\[0\]\?\.key \|\| null/)
  assert.match(source, /:class="evaluationSummaryParts\.dominant\.key \? `summary-dominant-\$\{evaluationSummaryParts\.dominant\.key\}` : ''"/)
  assert.match(source, /<strong :key="evaluationSummaryParts\.motionKey" class="evaluation-summary-copy">/)
  assert.match(source, /当前由<span/)
  assert.match(source, /<\/span>主导，<template/)
  assert.match(source, /<\/template>作为辅助。/)
  assert.doesNotMatch(source, /阶段，结论仍需结合样本规模判断。/)
  assert.match(source, /summary-model-link summary-model-link-dominant/)
  assert.match(source, /summary-model-link summary-model-link-auxiliary/)
})

test('model detail rows animate when expanded or collapsed', async () => {
  const appSource = await readFile(new URL('./App.vue', import.meta.url), 'utf8')
  const styleSource = await readFile(new URL('./style.css', import.meta.url), 'utf8')

  assert.match(appSource, /import chevronDownIcon from '\.\/assets\/icons\/chevron-down\.svg'/)
  assert.match(appSource, /const hasManualModelDetailInteraction = ref\(false\)/)
  assert.match(appSource, /if \(hasManualModelDetailInteraction\.value\) \{\s+return null/)
  assert.match(appSource, /function toggleModelDetail\(key\) \{\s+hasManualModelDetailInteraction\.value = true/)
  assert.match(appSource, /function selectModelDetail\(key\) \{\s+hasManualModelDetailInteraction\.value = true/)
  assert.match(appSource, /<Transition name="model-row-detail">/)
  assert.match(appSource, /class="ui-line-icon model-expand-chevron"/)
  assert.match(appSource, /iconMask\(chevronDownIcon\)/)
  assert.match(appSource, /v-if="expandedModelDetailKey === row\.key" class="model-row-detail"/)
  assert.match(styleSource, /\.model-row-detail-enter-active,\s+\.model-row-detail-leave-active \{/)
  assert.match(styleSource, /\.model-row-detail-enter-from,\s+\.model-row-detail-leave-to \{/)
  assert.match(styleSource, /opacity 220ms ease/)
  assert.match(styleSource, /transform: translateY\(-6px\)/)
  assert.match(styleSource, /\.model-bars article\.expanded \.model-expand-chevron \{\s+transform: rotate\(180deg\);/)
})

test('disabled backtest models are de-emphasized and sorted last', async () => {
  const appSource = await readFile(new URL('./App.vue', import.meta.url), 'utf8')
  const styleSource = await readFile(new URL('./style.css', import.meta.url), 'utf8')

  assert.match(appSource, /const disabled = row\.status === 'disabled' \|\| weight <= ACTIVE_MODEL_WEIGHT_EPSILON/)
  assert.match(appSource, /if \(a\.disabled !== b\.disabled\) \{\s+return a\.disabled \? 1 : -1/)
  assert.match(appSource, /const defaultExpandedModelDetailKey = computed\(\(\) => modelEvaluationRows\.value\.find\(\(row\) => !row\.disabled\)\?\.key \|\| null\)/)
  assert.match(appSource, /if \(selectedKey && selectedRow && !collapsedModelDetailKeys\.value\.has\(selectedKey\)\) \{/)
  assert.doesNotMatch(appSource, /selectedRow && !selectedRow\.disabled/)
  assert.match(appSource, /disabled: row\.disabled/)
  assert.match(appSource, /class="disabled-model-badge"/)
  assert.match(appSource, /样本不足，暂未参与融合/)
  assert.match(styleSource, /\.model-bars article\.disabled,/)
  assert.match(styleSource, /\.model-bars article\.disabled \.model-row-progress b \{/)
  assert.match(styleSource, /\.disabled-model-badge/)
})

test('disabled fusion weight cards are dynamically de-emphasized', async () => {
  const appSource = await readFile(new URL('./App.vue', import.meta.url), 'utf8')
  const styleSource = await readFile(new URL('./style.css', import.meta.url), 'utf8')

  assert.match(appSource, /const disabled = weight <= ACTIVE_MODEL_WEIGHT_EPSILON \|\| modelDetailByKey\.value\.get\(key\)\?\.status === 'disabled'/)
  assert.match(appSource, /statusLabel: disabled \? '未启用' : weightDiagnosticText\(\{ weight \}\)/)
  assert.match(appSource, /statusTitle: disabled \? '样本不足，暂未参与融合' : `当前参与融合，权重 \$\{formatPercent\(weight\)\}`/)
  assert.match(appSource, /<em v-if="row\.disabled" class="fusion-disabled-badge">\{\{ row\.statusLabel \}\}<\/em>/)
  assert.match(appSource, /if \(row\.disabled\) \{\s+return `\$\{row\.label\}：\$\{row\.statusTitle\}`/)
  assert.match(appSource, /if \(row\?\.disabled\) \{\s+return 'disabled'/)
  assert.match(styleSource, /\.fusion-weight-card\.disabled,/)
  assert.match(styleSource, /\.fusion-disabled-badge/)
  assert.match(styleSource, /\.fusion-weight-card\.disabled b \{/)
})

test('rule model detail keeps only evidence and does not duplicate statistics charts', async () => {
  const appSource = await readFile(new URL('./App.vue', import.meta.url), 'utf8')
  const styleSource = await readFile(new URL('./style.css', import.meta.url), 'utf8')
  const detailSource = await readFile(new URL('./services/modelDetails.js', import.meta.url), 'utf8')

  assert.doesNotMatch(appSource, /function ruleSummaryMetrics\(model\)/)
  assert.doesNotMatch(appSource, /v-if="model\.key === 'rule'" class="rule-summary-panel"/)
  assert.doesNotMatch(appSource, /完整副词条分布请在统计页查看。/)
  assert.doesNotMatch(appSource, /v-if="model\.key === 'rule'" class="rule-deviation-chart"/)
  assert.doesNotMatch(appSource, /<strong>均衡线<\/strong>/)
  assert.doesNotMatch(detailSource, /均衡线/)
  assert.doesNotMatch(styleSource, /\.rule-summary-panel \{/)
  assert.doesNotMatch(styleSource, /\.rule-summary-metrics \{/)
})

test('evaluation metrics use backend values instead of preview fallbacks', async () => {
  const appSource = await readFile(new URL('./App.vue', import.meta.url), 'utf8')
  const detailSource = await readFile(new URL('./services/modelDetails.js', import.meta.url), 'utf8')

  assert.doesNotMatch(appSource, /preview:\s*(2\.16|0\.86|0\.11|0\.34|0\.52)/)
  assert.match(appSource, /if \(metric\.value == null\) \{\s+return '样本不足'/)
  assert.match(appSource, /const evaluationReady = computed\(\(\) => evaluation\.value\?\.status === 'ready'/)
  assert.doesNotMatch(detailSource, /MODEL_BACKTEST_PREVIEW/)
  assert.ok(detailSource.includes('hitRate: evaluation?.model_scores?.[key]?.hit_rate ?? null'))
  assert.ok(detailSource.includes('loss: evaluation?.model_scores?.[key]?.loss ?? null'))
})

test('evaluation page exposes evaluated sample counts and gates confidence labels', async () => {
  const appSource = await readFile(new URL('./App.vue', import.meta.url), 'utf8')
  const detailSource = await readFile(new URL('./services/modelDetails.js', import.meta.url), 'utf8')

  assert.ok(detailSource.includes('evaluated: evaluation?.model_scores?.[key]?.evaluated ?? 0'))
  assert.match(appSource, /const modelBacktestSummaryText = computed\(\(\) => \(modelBacktestSampleCount\.value \? `回测样本 \$\{modelBacktestSampleCount\.value\} 条` : '等待回测样本'\)\)/)
  assert.match(appSource, /<span :title="modelBacktestSummaryText">\{\{ modelBacktestSummaryText \}\}<\/span>/)
  assert.match(appSource, /:title="row\.evaluated \? `\$\{row\.label\}基于 \$\{row\.evaluated\} 条样本回测` : `\$\{row\.label\}等待回测样本`"/)
  assert.doesNotMatch(appSource, /function modelEvaluatedText/)
  assert.match(appSource, /isBest: !disabled && evaluationReady\.value && bestHitRate != null && row\.hitRate === bestHitRate/)
  assert.match(appSource, /if \(evaluation\.value && evaluation\.value\.status !== 'ready'\) \{\s+return '样本不足'/)
  assert.doesNotMatch(appSource, /<span>\{\{ modelEvaluatedText\(row\) \}\}<\/span>/)
})

test('coverage band nodes keep colored fills in dark mode', async () => {
  const appSource = await readFile(new URL('./App.vue', import.meta.url), 'utf8')
  const styleSource = await readFile(new URL('./style.css', import.meta.url), 'utf8')

  assert.match(appSource, /class="coverage-band-node"/)
  assert.match(appSource, /:class="coverageNodeClass\(index\)"/)
  assert.match(styleSource, /--coverage-node-color: #1769d2;/)
  assert.match(styleSource, /--coverage-node-glow: rgba\(23, 105, 210, 0\.24\);/)
  assert.match(styleSource, /\.coverage-band-node\.middle \{\s+--coverage-node-color: #218b93;/)
  assert.match(styleSource, /\.coverage-band-node\.end \{\s+--coverage-node-color: #2c9f70;/)
  assert.match(styleSource, /border: 1px solid rgba\(255, 255, 255, 0\.86\);/)
  assert.match(styleSource, /\.app-shell\.theme-dark \.coverage-band-node \{\s+border-color: rgba\(237, 244, 248, 0\.32\);/)
  assert.match(styleSource, /inset 0 1px 0 rgba\(255, 255, 255, 0\.24\);/)
  assert.doesNotMatch(styleSource, /\.app-shell\.theme-dark \.sample-stage-marker,\s+\.app-shell\.theme-dark \.coverage-band-node/)
})

test('stats page focuses on analytics charts instead of prediction diagnostics', async () => {
  const appSource = await readFile(new URL('./App.vue', import.meta.url), 'utf8')
  const styleSource = await readFile(new URL('./style.css', import.meta.url), 'utf8')

  assert.doesNotMatch(appSource, /class="product-panel prediction-strip stats-prediction-strip"/)
  assert.doesNotMatch(appSource, /<h2>预测依据<\/h2>/)
  assert.match(appSource, /class="stats-summary-bar"/)
  assert.match(appSource, /:class="item.tone"/)
  assert.match(appSource, /:title="item.title"/)
  assert.doesNotMatch(appSource, /class="stats-diagnostic-pill"/)
  assert.match(appSource, /基于 \$\{stats\.total_rolls \|\| 0\} 条样本/)
  assert.match(appSource, /class="stats-empty-state"/)
  assert.match(appSource, /class="substat-deviation-chart"/)
  assert.match(appSource, /class="deviation-axis-scale"/)
  assert.match(appSource, /class="sample-stage-axis"/)
  assert.match(appSource, /class="sample-stage-marker"/)
  assert.match(appSource, /stage\.current/)
  assert.match(appSource, /<em v-if="stage\.current">当前<\/em>/)
  assert.match(appSource, /class="stats-chart-card sample-stage-card"/)
  assert.doesNotMatch(appSource, /context-progress-list/)
  assert.doesNotMatch(appSource, /最大偏高/)
  assert.doesNotMatch(appSource, /最大偏低/)
  assert.match(appSource, /当前偏高/)
  assert.match(appSource, /当前偏低/)
  assert.doesNotMatch(appSource, /上下文监控/)
  assert.match(appSource, /v-for="row in sortedStatFrequency"/)
  assert.match(appSource, /v-for="stage in sampleStageAxisRows"/)
  assert.doesNotMatch(appSource, /contextProgressRows/)
  assert.match(styleSource, /\.substat-deviation-row \{/)
  assert.match(styleSource, /\.deviation-axis-scale \{/)
  assert.match(styleSource, /\.sample-stage-marker \{/)
  assert.match(styleSource, /\.stats-empty-state \{/)
  assert.match(styleSource, /\.sample-stage-axis article\.current em \{/)
  assert.match(styleSource, /\.sample-stage-axis \{/)
  assert.match(styleSource, /\.sample-stage-card \{/)
  assert.match(styleSource, /grid-template-columns: minmax\(0, 1fr\);/)
  assert.doesNotMatch(styleSource, /\.context-progress-row \{/)
})
