# Generated by Django 6.0.4 on 2026-06-06 17:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('echoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecognitionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=80)),
                ('client_version', models.CharField(blank=True, max_length=40)),
                ('game_window_title', models.CharField(blank=True, max_length=160)),
                ('screen_resolution', models.CharField(blank=True, max_length=40)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('expired', 'Expired')], default='active', max_length=20)),
                ('snapshot_count', models.PositiveIntegerField(default=0)),
                ('saved_roll_count', models.PositiveIntegerField(default=0)),
                ('created_echo_count', models.PositiveIntegerField(default=0)),
                ('updated_echo_count', models.PositiveIntegerField(default=0)),
                ('conflict_count', models.PositiveIntegerField(default=0)),
                ('reverted_count', models.PositiveIntegerField(default=0)),
                ('last_snapshot_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognition_sessions', to='accounts.gameaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognition_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_recognitionsession',
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RecognitionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('enhance_success', 'Enhance success'), ('manual_rescan', 'Manual rescan'), ('sample_payload', 'Sample payload')], default='sample_payload', max_length=24)),
                ('client_event_id', models.CharField(blank=True, max_length=120)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('popup_delta_raw', models.JSONField(blank=True, default=dict)),
                ('detail_snapshot_raw', models.JSONField(blank=True, default=dict)),
                ('normalized_snapshot', models.JSONField(blank=True, default=dict)),
                ('field_confidence', models.JSONField(blank=True, default=dict)),
                ('popup_screenshot_hash', models.CharField(blank=True, max_length=128)),
                ('detail_screenshot_hash', models.CharField(blank=True, max_length=128)),
                ('match_status', models.CharField(choices=[('exact', 'Exact'), ('probable', 'Probable'), ('time_order', 'Time order'), ('created', 'Created'), ('conflict', 'Conflict')], default='created', max_length=20)),
                ('status', models.CharField(choices=[('saved', 'Saved'), ('ignored_duplicate', 'Ignored duplicate'), ('conflict', 'Conflict'), ('rejected', 'Rejected'), ('reverted', 'Reverted')], default='saved', max_length=24)),
                ('created_roll_ids', models.JSONField(blank=True, default=list)),
                ('created_roll_count', models.PositiveIntegerField(default=0)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_echo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_recognition_snapshots', to='echoes.echorecord')),
                ('game_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognition_snapshots', to='accounts.gameaccount')),
                ('matched_echo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_recognition_snapshots', to='echoes.echorecord')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='recognition.recognitionsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognition_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_recognitionsnapshot',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='recognitionsession',
            index=models.Index(fields=['game_account', 'status'], name='api_recogni_game_ac_08899e_idx'),
        ),
        migrations.AddIndex(
            model_name='recognitionsession',
            index=models.Index(fields=['game_account', 'started_at'], name='api_recogni_game_ac_ae5132_idx'),
        ),
        migrations.AddIndex(
            model_name='recognitionsession',
            index=models.Index(fields=['user', 'started_at'], name='api_recogni_user_id_6d2420_idx'),
        ),
        migrations.AddIndex(
            model_name='recognitionsnapshot',
            index=models.Index(fields=['game_account', 'status'], name='api_recogni_game_ac_67eab8_idx'),
        ),
        migrations.AddIndex(
            model_name='recognitionsnapshot',
            index=models.Index(fields=['game_account', 'match_status'], name='api_recogni_game_ac_a4c8c7_idx'),
        ),
        migrations.AddIndex(
            model_name='recognitionsnapshot',
            index=models.Index(fields=['session', 'created_at'], name='api_recogni_session_79cdb2_idx'),
        ),
        migrations.AddIndex(
            model_name='recognitionsnapshot',
            index=models.Index(fields=['user', 'created_at'], name='api_recogni_user_id_be9090_idx'),
        ),
        migrations.AddConstraint(
            model_name='recognitionsnapshot',
            constraint=models.UniqueConstraint(condition=models.Q(('client_event_id', ''), _negated=True), fields=('session', 'client_event_id'), name='unique_snapshot_client_event_per_session'),
        ),
        migrations.AddConstraint(
            model_name='recognitionsnapshot',
            constraint=models.UniqueConstraint(condition=models.Q(('detail_screenshot_hash', ''), _negated=True), fields=('game_account', 'detail_screenshot_hash'), name='unique_snapshot_detail_hash_per_game_account'),
        ),
    ]
