"""
Django settings for wuwa project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

LOCAL_DEVELOPMENT_DB_PASSWORD = 'root'
LOCAL_DEVELOPMENT_SECRET_KEY = 'wuwa-local-development-only-not-for-production'
LOCAL_HOSTS = ['127.0.0.1', 'localhost']
LOCAL_WEB_ORIGINS = [
    'http://127.0.0.1:5173',
    'http://localhost:5173',
]


def env_bool(name, default):
    value = os.environ.get(name)
    if value is None:
        return default

    normalized = value.strip().lower()
    if normalized in {'1', 'true', 'yes', 'on'}:
        return True
    if normalized in {'0', 'false', 'no', 'off'}:
        return False
    raise ImproperlyConfigured(f'{name} must be a boolean value')


def env_list(name, default):
    value = os.environ.get(name)
    if value is None:
        return list(default)
    return [item.strip() for item in value.split(',') if item.strip()]


def env_int(name, default):
    try:
        return int(os.environ.get(name, default))
    except (TypeError, ValueError):
        return default


WUWA_ENV = os.environ.get('WUWA_ENV', 'development').strip().lower()
if WUWA_ENV not in {'development', 'production'}:
    raise ImproperlyConfigured(
        'WUWA_ENV must be either development or production'
    )
IS_PRODUCTION = WUWA_ENV == 'production'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# The fallback is an explicit local-development convenience, never a production key.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    '' if IS_PRODUCTION else LOCAL_DEVELOPMENT_SECRET_KEY,
)

DEBUG = env_bool('DJANGO_DEBUG', not IS_PRODUCTION)

# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'accounts',
    'echoes',
    'recognition',
    'analytics',
    'api',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'wuwa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wuwa.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'wuwa_dev'),
        'USER': os.environ.get('DB_USER', 'PostgreSQL'),
        'PASSWORD': os.environ.get(
            'DB_PASSWORD',
            '' if IS_PRODUCTION else LOCAL_DEVELOPMENT_DB_PASSWORD,
        ),
        'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DB_PORT', '5432'),
        'CONN_MAX_AGE': env_int('DB_CONN_MAX_AGE', 60),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

SECURE_PROXY_SSL_HEADER = (
    ('HTTP_X_FORWARDED_PROTO', 'https') if IS_PRODUCTION else None
)
SECURE_SSL_REDIRECT = IS_PRODUCTION
SESSION_COOKIE_SECURE = IS_PRODUCTION
CSRF_COOKIE_SECURE = IS_PRODUCTION
SECURE_HSTS_SECONDS = env_int(
    'DJANGO_SECURE_HSTS_SECONDS',
    3600 if IS_PRODUCTION else 0,
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
    'DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS',
    False,
)
SECURE_HSTS_PRELOAD = env_bool('DJANGO_SECURE_HSTS_PRELOAD', False)

ALLOWED_HOSTS = env_list(
    'DJANGO_ALLOWED_HOSTS',
    [] if IS_PRODUCTION else LOCAL_HOSTS,
)

CORS_ALLOWED_ORIGINS = env_list(
    'DJANGO_CORS_ALLOWED_ORIGINS',
    [] if IS_PRODUCTION else LOCAL_WEB_ORIGINS,
)

CSRF_TRUSTED_ORIGINS = env_list(
    'DJANGO_CSRF_TRUSTED_ORIGINS',
    [] if IS_PRODUCTION else LOCAL_WEB_ORIGINS,
)

if IS_PRODUCTION:
    missing_production_settings = [
        name
        for name, value in (
            ('DJANGO_SECRET_KEY', SECRET_KEY),
            ('DB_PASSWORD', DATABASES['default']['PASSWORD']),
            ('DJANGO_ALLOWED_HOSTS', ALLOWED_HOSTS),
        )
        if not value
    ]
    if missing_production_settings:
        raise ImproperlyConfigured(
            'Production configuration requires: '
            + ', '.join(missing_production_settings)
        )
    if DEBUG:
        raise ImproperlyConfigured(
            'DJANGO_DEBUG must be false in production'
        )
