# Generated by Django 6.0.4 on 2026-06-06 17:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EchoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('echo_uid', models.CharField(max_length=80)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('cost', models.PositiveSmallIntegerField()),
                ('set_name', models.CharField(max_length=120)),
                ('main_stat', models.CharField(max_length=80)),
                ('source', models.CharField(blank=True, max_length=160)),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('assistant', 'Assistant'), ('import', 'Import')], default='manual', max_length=20)),
                ('tuning_batch_id', models.CharField(blank=True, max_length=120)),
                ('is_continuous_tuning', models.BooleanField(default=False)),
                ('auto_imported', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('archived', 'Archived')], default='in_progress', max_length=20)),
                ('last_tuned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echo_records', to='accounts.gameaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echo_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_echorecord',
                'ordering': ['-last_tuned_at', '-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SubstatRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('substat_type', models.CharField(max_length=80)),
                ('tier_value', models.FloatField()),
                ('tuned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('enhance_phase', models.CharField(blank=True, choices=[('+5', '+5'), ('+10', '+10'), ('+15', '+15'), ('+20', '+20'), ('+25', '+25')], max_length=8)),
                ('tuning_order', models.PositiveIntegerField(blank=True, null=True)),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('assistant', 'Assistant'), ('import', 'Import')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('echo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substat_rolls', to='echoes.echorecord')),
            ],
            options={
                'db_table': 'api_substatroll',
                'ordering': ['position', 'id'],
            },
        ),
    ]
