# Generated by Django 6.0.4 on 2026-06-06 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('echoes', '0001_initial'),
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='substatroll',
            name='recognition_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rolls', to='recognition.recognitionsnapshot'),
        ),
        migrations.AddIndex(
            model_name='echorecord',
            index=models.Index(fields=['game_account', 'status'], name='api_echorec_game_ac_6b7675_idx'),
        ),
        migrations.AddIndex(
            model_name='echorecord',
            index=models.Index(fields=['game_account', 'last_tuned_at'], name='api_echorec_game_ac_81c12f_idx'),
        ),
        migrations.AddIndex(
            model_name='echorecord',
            index=models.Index(fields=['game_account', 'created_at'], name='api_echorec_game_ac_e4cfd7_idx'),
        ),
        migrations.AddConstraint(
            model_name='echorecord',
            constraint=models.UniqueConstraint(fields=('game_account', 'echo_uid'), name='unique_echo_uid_per_game_account'),
        ),
        migrations.AddIndex(
            model_name='substatroll',
            index=models.Index(fields=['echo'], name='api_substat_echo_id_fdf0d4_idx'),
        ),
        migrations.AddIndex(
            model_name='substatroll',
            index=models.Index(fields=['tuned_at'], name='api_substat_tuned_a_d8188e_idx'),
        ),
        migrations.AddIndex(
            model_name='substatroll',
            index=models.Index(fields=['substat_type'], name='api_substat_substat_89302f_idx'),
        ),
        migrations.AddIndex(
            model_name='substatroll',
            index=models.Index(fields=['echo', 'position'], name='api_substat_echo_id_698f5b_idx'),
        ),
        migrations.AddConstraint(
            model_name='substatroll',
            constraint=models.UniqueConstraint(fields=('echo', 'position'), name='unique_substat_position_per_echo'),
        ),
        migrations.AddConstraint(
            model_name='substatroll',
            constraint=models.UniqueConstraint(fields=('echo', 'substat_type'), name='unique_substat_type_per_echo'),
        ),
        migrations.AddConstraint(
            model_name='substatroll',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1), ('position__lte', 5)), name='substat_position_1_to_5'),
        ),
    ]
