# Generated by Codex on 2026-07-05

from django.db import migrations, models
from django.db.models import F


def backfill_echo_names(apps, schema_editor):
    EchoRecord = apps.get_model("echoes", "EchoRecord")
    EchoRecord.objects.filter(echo_name="", display_name__gt="").update(echo_name=F("display_name"))


class Migration(migrations.Migration):

    dependencies = [
        ("echoes", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="echorecord",
            name="echo_asset_id",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="echorecord",
            name="echo_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="echorecord",
            name="echo_image",
            field=models.CharField(blank=True, max_length=260),
        ),
        migrations.RunPython(backfill_echo_names, migrations.RunPython.noop),
    ]
