# Generated by Django 6.0.4 on 2026-06-06 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=32)),
                ('server', models.CharField(blank=True, max_length=32)),
                ('nickname', models.CharField(blank=True, max_length=80)),
                ('is_default', models.BooleanField(default=False)),
                ('next_echo_sequence', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_gameaccount',
                'ordering': ['-is_default', '-updated_at', '-id'],
                'indexes': [models.Index(fields=['user', 'is_default'], name='api_gameacc_user_id_96e728_idx'), models.Index(fields=['user', 'uid', 'server'], name='api_gameacc_user_id_0ef2f6_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('uid', ''), _negated=True), fields=('user', 'uid', 'server'), name='unique_bound_game_account_per_user'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='unique_default_game_account_per_user')],
            },
        ),
    ]
